### ISSUE TITLE
Redirect loop (error too many redirects) with v 1.13.0

### ISSUE THREAD

**Issue by BorisTheSlavKing** [engintron/engintron#1224] opened 2020-08-10 09:43 UTC
Hey all,

just upgraded my Engintron and now all the sites on my server keep getting error too many redirect errors. I have tried to search for the issue but am unable to find it. It works for about 30min after I reboot enginton but again dies.

`Show loaded modules...
Loaded Modules:
 core_module (static)
 so_module (static)
 http_module (static)
 mpm_event_module (shared)
 cgid_module (shared)
 access_compat_module (shared)
 actions_module (shared)
 alias_module (shared)
 auth_basic_module (shared)
 authn_core_module (shared)
 authn_file_module (shared)
 authz_core_module (shared)
 authz_groupfile_module (shared)
 authz_host_module (shared)
 authz_user_module (shared)
 autoindex_module (shared)
 deflate_module (shared)
 dir_module (shared)
 env_module (shared)
 expires_module (shared)
 filter_module (shared)
 headers_module (shared)
 include_module (shared)
 log_config_module (shared)
 logio_module (shared)
 mime_module (shared)
 negotiation_module (shared)
 proxy_module (shared)
 proxy_fcgi_module (shared)
 proxy_http_module (shared)
 proxy_wstunnel_module (shared)
 remoteip_module (shared)
 rewrite_module (shared)
 setenvif_module (shared)
 slotmem_shm_module (shared)
 socache_dbm_module (shared)
 socache_shmcb_module (shared)
 socache_redis_module (shared)
 status_module (shared)
 suexec_module (shared)
 unique_id_module (shared)
 unixd_module (shared)
 userdir_module (shared)
 version_module (shared)
 bwlimited_module (shared)
 ssl_module (shared)
 http2_module (shared)
 security2_module (shared)
 suphp_module (shared)`

`*** System Info ***

Uptime: 11:41:38 up 1 day, 17:55,  0 users,  load average: 0.43, 0.21, 0.21

OS: CentOS Linux release 7.8.2003 (Core)

Kernel: Linux superodmainname.com 3.10.0-1127.18.2.el7.x86_64 #1 SMP Sun Jul 26 15:27:06 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

Processors: 6 CPU(s)

RAM: 15.51 GB

Memory Usage:
              total        used        free      shared  buff/cache   available
Mem:          15884        3157        9817         308        2909       12135
Swap:             0           0           0

Disk Usage:
Filesystem     Type      Size  Used Avail Use% Mounted on
devtmpfs       devtmpfs  7.8G     0  7.8G   0% /dev
tmpfs          tmpfs     7.8G     0  7.8G   0% /dev/shm
tmpfs          tmpfs     7.8G   41M  7.8G   1% /run
tmpfs          tmpfs     7.8G     0  7.8G   0% /sys/fs/cgroup
/dev/sda2      ext4      393G  337G   37G  91% /
/dev/sda1      ext4      969M  258M  645M  29% /boot
/dev/loop0     ext4      3.9G   20M  3.6G   1% /tmp
tmpfs          tmpfs     1.6G     0  1.6G   0% /run/user/0

Nginx Cache/Temp Disk Usage:
62M	/var/cache/nginx/engintron_dynamic
64M	/var/cache/nginx/engintron_static
4.0K	/var/cache/nginx/engintron_temp

System Time: Mon Aug 10 11:41:38 CEST 2020

System Users Connected:
11:41:38 up 1 day, 17:55,  0 users,  load average: 0.43, 0.21, 0.21
USER     TTY      FROM             LOGIN@   IDLE   JCPU   PCPU WHAT`

There is nothing in the logs, to help solve this issue. Does anyone else have the same issues?

**Comment by fevangelou** [comment] 2020-08-18 21:20
Engintron's Nginx does not do any sort of redirects on its own. So it's probably a combination of .htaccess redirects and PHP redirects causing the loops.

Why this issue surfaced now of course is a different story...

**Comment by r-per** [comment] 2020-08-20 09:42
Same incidence as BorisTheSlavKing. Similar environment, Cloudlinux + Cpanel 6 CPU (s) RAM: 32 GB + Memcached.  Indicate that the incidence occurs mainly in websites running WordPress with the WP Super Caché plugin.

**Comment by r-per** [comment] 2020-08-23 19:56
Thanks, I'll look into it. But for 5 months no problem (the content of the sites has not been changed). We have only updated Easyapache.

**Comment by fevangelou** [comment] 2020-08-24 12:33
Unless these sites are fully custom made, then in these 5 months, they may have been updated to newer CMS versions or newer plugin/extension versions.

**Comment by webaholicsteam** [comment] 2020-09-02 23:07
I just updated to 1.13 and the next day I started having this problem on several client sites but not all, looked in to common plugins they all use the same so not what it could be.

**Comment by tvoltolini88** [comment] 2020-09-04 16:08
Hello.
Seeing the same behavior after updating to 1.13.
I updated 4 servers to 1.13 and sites (mainly wordpress) started to show redirect loops. 
Removing htaccess and disabling plugins didn't help so I copyed the /etc/nginx/ folder from another server that was still running v1.11 and the loop was gone.
I even tryed to copy specific blocks of code from v1.11 but I couln't figured it out exactly what it causing the issue. I ended up rsyncing the whole folder because I was running out of time. It's fixed now but all servers are running the old version.

Also, thanks @fevangelou for the amazing work in this project.

**Comment by fevangelou** [comment] 2020-09-04 17:28
There are no changes between 1.11 and 1.13 in the Nginx configs that would produce such redirect issues. Send me an actual problematic URL if possible to test remotely...

**Comment by webaholicsteam** [comment] 2020-09-04 18:11
nichehomes.com and motionstate.com but currently i have engintron disabled because after enabling 1.13 about 3 minutes later the redirect issue occurs. would you like me to enable it now?

**Comment by veryDead** [comment] 2020-09-04 21:59
Hello, I can verify that this is also happening on my server to a single domain. All sites were happily running on 1.11 for weeks, and I did an upgrade to 1.13 this morning and within 5 minutes the site went into a 301 redirect loop and errored out. The only way to fix it is to purge the engintron cache. The site will run for a random length of time with no issues and then just stop working.

I have bypassed caching for the site for the time being and that has worked at preventing the problem. Whatever the problem, engintron 1.11 did not have an issue with the site, only 1.13 does.

**Comment by fevangelou** [comment] 2020-09-08 11:27
@veryDead Did you check that site's .htaccess file for anything weird?

**Comment by veryDead** [comment] 2020-09-08 16:06
I did, and it is all basic drupal/cpanel php redirects that work fine on engintron 1.11. Absolutely no changes have been made between it working correctly on v1.11 and failing on v1.13.

I attached an anonymized version of the .htaccess file to this post for your review. It is standard drupal htaccess with some caching settings, some ssl redirects, and was happily working with all previous versions of engintron up to 1.13. I've been using engintron for this site for more than 2 years without issue and the .htaccess hasn't been changed in 5 months according to the file date and comparing with my archived previous version. I also verified that no new drupal modules were installed between 1.11 and 1.13 engintron versions.
[htaccess-001.txt](https://github.com/engintron/engintron/files/5189484/htaccess-001.txt)

**Comment by BorisTheSlavKing** [comment] 2020-09-09 21:53
Just a quick question. Are we perhaps all using CloudFlare? The issue seems to be gone for me after disabling CloudFlares caching

**Comment by veryDead** [comment] 2020-09-14 15:16
I'm not using cloudflare and still getting this problem.

**Comment by webaholicsteam** [comment] 2020-09-18 18:13
I still have engintron disabled, is there a solution in progress here?

**Comment by fevangelou** [comment] 2020-09-19 07:09
The issue seems to be site specific. Do some digging on your own guys...

**Comment by mblendinger** [comment] 2020-09-19 15:57
same problem here.

**Comment by mblendinger** [comment] 2020-09-19 16:16
note: the problem is with websites using CloudFlare, try changing settings, like ssl settings,but I cant found a silver bullet

**Comment by fevangelou** [comment] 2020-09-21 17:39
@mblendinger Your issue is probably different, so please do not cross-post :)

**Comment by webaholicsteam** [comment] 2020-09-29 19:58
Found the solution, at least for me. I had to go through MultiPHP Manager in WHM and reset the PHP version from 7.3 (or whatever it was per site) then set it back to 7.3 also uncheck PHP-FPM and Recheck. The theory is this basically reset the apache/PHP settings for the affected accounts (I had about 20 out of 100 or so affected).

After setting PHP back and forth again, you just need to go to engintron settings and purge the cache & temp files.

**Comment by fevangelou** [comment] 2020-09-29 20:24
@webaholicsteam Keep in mind that when doing these actions, cPanel will also rewrite (correct) the domain's .htaccess file in regards to its cPanel specific configuration (e.g. the PHP version).

**Comment by webaholicsteam** [comment] 2020-09-29 20:26
yes, and that is what I thought was fixing it, but after 30 minutes now motionstate.com is now having the redirect loop issue, so i guess it didnt work as expected. is there a way to pay for your support to have you login and check our system?

**Comment by fevangelou** [comment] 2020-09-29 20:56
@webaholicsteam Sure, have a look here: https://github.com/engintron/engintron#commercial-support--server-optimization-services

**Comment by BorisTheSlavKing** [comment] 2020-10-07 15:47
Just a heads-up fully remove engintron before doing the latest cPanel update if you are having the issue above. 4 of my servers with this issue crashed (WHM still works but Apache is now in a constant loop) 2 that did not have this issue work fine.

It's a bit bothersome solving it since my VPS and cPanel licence is provided by my hosting provider (Contabo) and I am unable to contact cPanel directly and the hosting provider is giving me tips to minimize sizes of my images and that it should help :) (I read this suggestion a few times to make sure they weren't joking).

When I solve this I will post the results. Hopefully, I won't throw everything away and just reinstall the server without Engintron ofc.

**Comment by tvoltolini88** [comment] 2020-10-07 18:04
@BorisTheSlavKing Not related to engintron but you can contact cPanel directly on tickets.cpanel.net, even if you buy your license from a 3rd party.

Did not see erros on any of my servers while updating cpanel to v90, but i'm still using engintron v1.11 and v1.12 on all servers.

**Comment by fevangelou** [comment] 2020-10-09 15:46
@BorisTheSlavKing As @tvoltolini88 rightfully mentioned, you may be paying the license for cPanel via Contabo, but you're still entitled to cPanel support. Send a ticket directly via WHM.

**Comment by webaholicsteam** [comment] 2020-10-09 18:35
So am I to understand that I should fully remove engintron then update cPanel then reinstall engintron to fix this issue?

**Comment by fevangelou** [comment] 2020-10-10 07:31
@webaholicsteam I doubt that's needed... Simply locate the affected sites. If every site is affected, maybe you have a common include in Apache (some leftover from the past).

**Comment by webaholicsteam** [comment] 2020-10-10 20:31
@fevangelou did you get my email with the affected sites? it was only like 5 out of 100, I also sent server creds.

**Comment by fedealvz** [comment] 2020-10-24 16:31
The same thing happens to me in 1.13.0 on sites that don't use Cloudflare.

If I add "?nocache" to bypass Nginx it access the site ok.

And clearing the Engintron cache with "Purge cache & temp files" option solves the problem, but sometimes it happens again.

**Comment by fevangelou** [comment] 2020-10-24 17:15
The issue is probably your .htaccess redirects (or site code that sends bad HTTP headers).

There is more insight here: https://github.com/engintron/engintron/issues/1232

Closing this thread to merge the discussion with the one above.

**Closed by fevangelou** 2020-10-24 17:15 UTC
