### ISSUE TITLE
Webmail not working

### ISSUE THREAD

**Issue by JorgeMarcelino-HS** [engintron/engintron#864] opened 2018-06-14 12:25 UTC
Hi, Any subdomain with webmail. does not work in the new version.

Example: webmail.dominio.com Please fix this problem!

**Comment by dnoguera** [comment] 2018-06-15 09:11
I have the same problem, when trying to login in Horde or Swquierremail using webmail.domain.com, I get a blank page... However, RoundCube works well any idea?

Thanks!

**Comment by AnoopAlias** [comment] 2018-06-15 09:50
This error seems to be caused by a change at cPanel side as I see the same issue on another nginx plugin too

Chrome inspect show

```
cpanel-all-min.js?locale=en&locale_revision=1528153585:79 Uncaught DOMException: Failed to read the 'contentDocument' property from 'HTMLIFrameElement': Blocked a frame with origin "http://webmail.xxxxxx.yy" from accessing a cross-origin frame.
    at contents (http://webmail.xxxxxxx.yy/cPanel_magic_revision_1525820789/cjt/cpanel-all-min.js?locale=en&locale_revision=1528153585:79:16256)
```

**Comment by AnoopAlias** [comment] 2018-06-15 09:53
Perhaps cPanel added a CORS header somewhere causing this issue.

There is no error in /usr/local/cpanel/logs/error_log unfortunately

**Comment by AnoopAlias** [comment] 2018-06-15 10:02
As an update, this issue is not Nginx related as I was able to reproduce this in a server which doesn't have Nginx running. cPanel broke something in their upgrade. You should contact cPanel support and have them release a patch/fix

**Comment by JorgeMarcelino-HS** [comment] 2018-06-15 10:42
@AnoopAlias Hello, You're wrong, when we deactivate Engintron it works perfectly!
Also, we uninstalled on one of the servers for testing and also works without Engintron.

**Comment by fevangelou** [comment] 2018-06-15 11:56
It's a proxy issue in Horde and SquirrelMail specifically. FYI, SquirrelMail will soon be removed from cPanel. Congratulate anyone using Horde. The future is Roundcube. So don't sweat to much. If you STILL wanna use Horde, add a ticket to cPanel support so they can investigate the issue further.

**Comment by fevangelou** [comment] 2018-06-15 11:57
FYI https://blog.cpanel.com/the-death-of-squirrelmail/

**Comment by fevangelou** [comment] 2018-06-15 12:00
Personally, I would disable Horde & SquirrelMail in "Tweak Settings" (in WHM), keep Roundcube and also add AfterLogic's WebMail Lite PHP which has a cPanel installer https://afterlogic.org/download/webmail-lite-php?platform=cpanel-installer and honestly it's the prettiest of all to use.

**Comment by JorgeMarcelino-HS** [comment] 2018-06-15 13:55
@fevangelou  Hi, Roundcube also presents problems here when trying to access webmail.domain.com gets everything "broken".

**Comment by fevangelou** [comment] 2018-06-15 13:56
Not in my tests. Make sure you are using the latest release of Engintron and cPanel.

**Comment by JorgeMarcelino-HS** [comment] 2018-06-15 13:58
STABLE 70.0.48

**Comment by AnoopAlias** [comment] 2018-06-15 14:13
This is really strange as on a test account with Nginx ( not Engintron, but proxied similarly like Engintron), horde works fine too - See screenshot with headers - http://i.imgur.com/pWOuBnI.png
But I encountered the webmail timing out in another server with and without Nginx. So doubting a tweak setting as I am not able to consistently reproduce this on cPanel 70.0.48

**Comment by AnoopAlias** [comment] 2018-06-15 14:45
Ok, I found the difference between the machine that loads Horde and that doesn't. It was CSF

If I disable CSF on the machine where horde times out; it starts to work again

@JorgeMarcelino-HS  - Can you try disabling all firewall rules (disable CSF if present) and see if you can load horde over webmail.domain.com

**Comment by AnoopAlias** [comment] 2018-06-15 14:51
I can confirm the cause is CSF on the test from multiple machines. Exactly what rule in CSF eludes me

**Comment by JorgeMarcelino-HS** [comment] 2018-06-15 14:54
@AnoopAlias We already did that and it did not work.

**Comment by dnoguera** [comment] 2018-06-15 14:58
Hi, in my test, disabling CSF doesn't work. @AnoopAlias  could you please paste here your Nginx configuration in your webmail Vhost ?

Thanks!

**Comment by AnoopAlias** [comment] 2018-06-15 15:10
Its just a proxy to httpd config. The webmail.domain.com is handled by apache 

I have further narrowed it down to having the httpd ssl and non-ssl ports allowed in TCP_IN and TCP_OUT in csf 

Note that I am not using Engintron , but a similar software . 



```
################### Proxy Subdomains ###################

server {
listen    xxxx:80 ;


listen    xxxx:443 ssl http2 ;

ssl_certificate /var/cpanel/ssl/apache_tls/x.com/combined;
ssl_certificate_key /var/cpanel/ssl/apache_tls/x.com/combined;

ssl_prefer_server_ciphers on;
ssl_ciphers "EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH";
ssl_session_cache shared:SSL:50m;
ssl_dhparam /etc/nginx/ssl/dhparam.pem;
ssl_session_timeout  10m;
ssl_stapling on;
ssl_stapling_verify on;

server_name webmail.x.com ;
location / {
   proxy_send_timeout   90;
   proxy_read_timeout   90;
   proxy_buffer_size    4k;
   proxy_buffers     16 32k;
   proxy_busy_buffers_size 64k;
   proxy_temp_file_write_size 64k;
   proxy_connect_timeout 30s;
   proxy_pass   $scheme://xxx:$cpport;
   proxy_set_header   Host   $host;
   proxy_set_header   X-Real-IP  $remote_addr;
   proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
  }
}

################### Proxy Subdomains ###################

```

**Comment by AnoopAlias** [comment] 2018-06-15 16:16
Ref: https://forums.cpanel.net/threads/nginx-proxy-not-able-to-display-squirrelmail.631219/

**Comment by dnoguera** [comment] 2018-06-15 16:42
OK thanks for sharing! I will test your config with Horde and update here my results...  I sended yesterday a support request, but they always respond me saying that this is a Nginx problem and they do not support 3rd party software...

**Comment by AnoopAlias** [comment] 2018-06-16 04:11
Ok more info on this:

The cPanel Proxy Subdomain is sending out links of the format https://webmail.domain.com:alt-http-port

http://i.imgur.com/4m1m4MK.png

You can see the Server: header as Apache and port as 4430(the alt port I am using) , instead of the default 443 and Nginx as server on the request and response header. So in this case, if the alt-ports are not whitelisted in CSF the webmail fails to load

This is why Horde loads fine with tweak in Firewall

As for Squirrelmail , the Application itself is setting a X-Frame-Options: SAMEORIGIN
header -- http://i.imgur.com/SyVyI8t.png  which cause the Frame to not load . But as mentioned Sqmail is a dead project, so having this working with SqMail is not crucial

**Comment by fevangelou** [comment] 2018-07-06 15:04
@AnoopAlias I opened up the ports in a stock cPanel + Engintron server and the issue was not solved. My guess is there is some header mixup and the redirection still fails. Keep in mind the redirection fails when you open up Horde using webmail.domain.tld to login, it does NOT fail when you go from cPanel's port.

**Comment by WhiteDogBe** [comment] 2018-08-04 18:40
I'm having the same problem where Horde is not working when accessed via webmail.domain.com. It shows a 404 error with a link to "servername.domain.com:8080/cpsess123456789/horde/login.php (port 8080)". Port 8080 is opened in CSF (also tried with CSF disabled).

I'm assuming this is something cPanel must fix (which they may or may not do). Is there some way to work around this in Engintron or Horde directly though?

**Comment by WhiteDogBe** [comment] 2018-08-05 18:43
I have Horde working again with Engintron :)

When I go into Engintron and change default.conf as following (comment out these 2 lines):
#proxy_set_header              X-Forwarded-Host $host;
#proxy_set_header              X-Forwarded-Port $server_port;

Then restart nginx. Horde now works via webmail.domain.com for me.

I'm assuming these headers are there for a reason though. As I just started using Engintron a few days ago, can someone else verify this and perhaps tell me how to set an exception where this is applied only for webmail.* links?

**Comment by fevangelou** [comment] 2018-08-05 19:49
The first line is for passing visitor info to Apache for logging.

It's easy to make exceptions.

Can you triple-verify though it works?

**Comment by WhiteDogBe** [comment] 2018-08-06 10:06
I did the same test on another cPanel server and have the same result.
Lines active > 404
Lines commented > Horde

Would be great i someone else could confirm.
Maybe cPanel is using the same headers internally and they get overwritten?

**Comment by JorgeMarcelino-HS** [comment] 2018-08-14 09:55
Any update?

**Comment by WhiteDogBe** [comment] 2018-08-14 20:41
For info, somewhat the same issue exists when you log into cPanel > Email Accounts > Access Webmail. You are then transferred to http://cpanel.1domain.tld/cpsess5757912667/frontend/paper_lantern/mail/webmailform.html... where you then choose Horde or RoundCube.

This is also solved by commenting out the 2 lines I mentioned earlier.

If there is a way to only make cpanel. and webmail. links not set that directive, an example and where that need to be added in Engintron would be much appreciated.

**Comment by JorgeMarcelino-HS** [comment] 2018-08-14 22:10
@WhiteDogBe Can you send a print of how the configuration was?

**Comment by WhiteDogBe** [comment] 2018-08-15 12:57
@JorgeMarcelino-HS as explained above, go into Engintron and change "proxy_params_common" as following (comment out these 2 lines):
#proxy_set_header X-Forwarded-Host $host;
#proxy_set_header X-Forwarded-Port $server_port;

**Comment by ddrhost** [comment] 2018-08-17 12:01
@WhiteDogBe his tip worked. Thank you.

**Comment by fevangelou** [comment] 2018-08-17 13:04
Actually, the issue is with `proxy_set_header X-Forwarded-Host $host` only. The port doesn't matter.

I'll revise the codebase to add an exception for webmail.*.

Thank you @WhiteDogBe for troubleshooting.

**Comment by JorgeMarcelino-HS** [comment] 2018-08-17 13:11
Hello, @WhiteDogBe I comment at the end of the file? in this way? SEE: https://prnt.sc/kjs3j8

**Comment by ddrhost** [comment] 2018-08-17 13:12
@JorgeMarcelino-HS no, there are the same lines to be discussed above.

**Comment by JorgeMarcelino-HS** [comment] 2018-08-17 13:15
Is correct? See: https://prnt.sc/kjs5w4

**Comment by ddrhost** [comment] 2018-08-17 13:15
@fevangelou also worked only with this line.

**Comment by ddrhost** [comment] 2018-08-17 13:16
@JorgeMarcelino-HS yes, but it can only be this 1 line quoted by @fevangelou.

**Comment by fevangelou** [comment] 2018-08-17 13:37
See this please: https://github.com/engintron/engintron/wiki/Changelog#august-17th-2018---v191

**Closed by fevangelou** 2018-08-17 13:37 UTC

**Comment by hyssop** [comment] 2018-12-15 10:17
I'm still seeing the issue of Horde and SqirrelMail giving 404 with Engintron enabled. If I disable it the webmail.domain.com works fine.

The change log says this was addressed in 1.9.1, but it was still failing, and I updated to 1.9.2 and it still is failing.

Is there something I'm missing or should check?

**Comment by bananacy** [comment] 2020-04-12 11:56
Hello,  webmail won't work. I use roundcube.
I was getting dns error, but after making above changes i now get certificate errors:

Your connection is not private
Attackers might be trying to steal your information from cpanel.domain.com (for example, passwords, messages, or credit cards). Learn more
NET::ERR_CERT_DATE_INVALID

**Comment by fevangelou** [comment] 2020-04-13 17:14
Gotta provide more context @bananacy.

**Comment by bananacy** [comment] 2020-04-13 20:28
Hello,

Yesterday Webmail.mydomai.com wouldn't load (basically after enabling Egintron for two days)
Then i added some custom rules i found to disable proxy_set_header, then main website site and webmail broke.
if ($host ~* "^(webmail|cpanel|whm|webdisk|cpcalendars|cpcontacts)\.") {
    set $PROXY_FORWARDED_HOST '';
}

ANYWAY, i Reinstalled Engintron and it now all works with custom rules above.
All good. I was too hurried to write here. But after some troubleshooting i figured it out.

:-)

**Comment by fevangelou** [comment] 2020-04-13 20:29
There are exceptions in place already for these subdomains. Anything special with your networking setup? E.g. are you behind a NAT or something?

**Comment by fevangelou** [comment] 2020-04-13 20:30
FYI: https://github.com/engintron/engintron/blob/master/nginx/common_http.conf#L39
