### ISSUE TITLE
Need restart after issueing SSL Certificates

### ISSUE THREAD

**Issue by greenwebbd** [engintron/engintron#589] opened 2017-07-18 12:23 UTC
Currently, we are using engintron on some of our web server as testing purpose. Unfornately, if the ssl issued by cpanel ( auto ssl ) it doesn't work until we restart the engintron and apache. 

This is really annoying for me to restart every time after creating cpanel account. Is there any automatic solution ? 

Regards
Jobayer Alam

**Comment by ramphy** [comment] 2017-07-18 13:03
https://github.com/engintron/engintron/issues/566#issuecomment-311133634

https://github.com/engintron/engintron/issues/582

**Comment by greenwebbd** [comment] 2017-07-18 14:50
my cron job 

SHELL=/bin/bash
PATH=/sbin:/bin:/usr/sbin:/usr/bin
MAILTO=root

# For details see man 4 crontabs

# Example of job definition:
# .---------------- minute (0 - 59)
# |  .------------- hour (0 - 23)
# |  |  .---------- day of month (1 - 31)
# |  |  |  .------- month (1 - 12) OR jan,feb,mar,apr ...
# |  |  |  |  .---- day of week (0 - 6) (Sunday=0 or 7) OR sun,mon,tue,wed,thu,fri,sat
# |  |  |  |  |
# *  *  *  *  * user-name  command to be executed

* * * * * root /etc/nginx/utilities/https_vhosts.sh >> /dev/null 2>&1


As you can see there is no error. i don't like to purge cache using cron that is not a good solution.

**Comment by fritolays** [comment] 2017-07-18 15:31
I believe the second issue #582 has a cron-less solution.
https://github.com/tgerov/engintron/blob/patch-1/nginx/utilities/https_vhosts.sh

I have yet to test it, but seems like it does purge & restart apache and nginx.

**Comment by jhawkins002** [comment] 2017-08-01 21:35
Hi all. Like others, we tried the above patch to no avail. We also just spent a week testing cPnginx, but have landed back here on Engintron for the time being since that tool had it's own issues and wasn't really a great fit for us. Across the board it's not a great time for NGINX on cPanel it seems!

Did some poking around under the hood today - and though I don't fully see why - I can confirm at least on our install that invoking "/engintron.sh restoreipfwd" reliably sorts new SSL hosts, where purgecaches and restarts did not. I have an idea to bolt the command onto an incron service that watches the /var/cpanel/ssl/installed/certs/ directory for updates.

I hope someone out there finds this useful until a more sanctioned fix rolls out for these issues.

**Comment by jhawkins002** [comment] 2017-08-02 13:46
Update: the solution above seems to be working! Here is the syntax we used:

`/var/cpanel/ssl/installed/certs IN_DELETE,IN_CLOSE_WRITE /engintron.sh restoreipfwd `

Basically, incron watches the installed/certs directory and whenever an item is edited, created, or deleted the engintron restoreipfwd script is invoked. Again - I have absolutely no idea why that command works more reliably for us than just a straightforward service restart or cache purge, but it does.

**Comment by fevangelou** [comment] 2017-08-02 14:03
@jhawkins002 I doubt `/engintron.sh restoreipfwd` does the trick beyond basically re-restarting Apache/Nginx for you.

I recommend you change your cron line to just use `/engintron.sh purgecache`.

The tests you mentioned could have been false if you were seeing a cached result. In other words, when checking something like that, always use a private browser window which you close after each test.

**Comment by fevangelou** [comment] 2017-08-02 14:16
Also see this: https://github.com/engintron/engintron/wiki/SSL-certificate-changes-not-visible-in-Nginx%3F-Here's-a-possible-explanation-&-solution

**Comment by jhawkins002** [comment] 2017-08-02 16:35
Thank you for the notes and advice!

Great share re: CRON; we have noted your earlier advice regarding CRON integrity, and have made sure it is clean. Unfortunately SSL still fails to light up when solely relying on the /etc/nginx/utilities/https_vhosts.sh script. 

Re: restoreipfwd - It appears that we spoke to soon anyway. Not too long after I posted this morning we tested a number of new domains that did not deploy properly, so it appears our first round of successful tests led us to a too optimistic conclusion. Furthermore after a NGINX restart an hour ago all domains across the web host are unresponsive over SSL with an error 503. That, as a matter of fact, has happened before and was the precipitating factor that led to us researching cPnginx. Disabling or removing Engintron breaks all connectivity to SSL completely. 

Fyi, when testing we always make sure that we dump client-side caches to make sure that doesn't contaminate results. We also test against newly created, unique temporary domains generated specifically for the purpose of troubleshooting NGINX.

**Comment by fevangelou** [comment] 2017-08-02 16:48
If you removed Engintron and the sites did not come up again, then the issue is probably a stuck installation of some other Nginx-for-cPanel plugin (cPnginx in this case or other). That previous installation is also the reason why Engintron did not properly work in the first place.

I've seen this before. You need to completely remove Engintron then remove any yum repositories that may stick around and cause issues.

Refer to the wiki for additional info on uninstalling other such plugins: https://github.com/engintron/engintron/wiki/How-to-uninstall-other-Nginx-plugins-for-cPanel-(before-installing-Engintron)

Keep in mind that Engintron has both an installation and un-installation policy. If you don't like it, it returns your system back to the state it was. Any, and I mean ANY, other plugin installing Nginx for cPanel does not either have a clear uninstall path or worse, does not really uninstall everything, leaving garbage in your system.

**Comment by jhawkins002** [comment] 2017-08-02 17:06
Oh fantastic - I definitely think some configuration cruft is at play, so this resource is very helpful!

**Comment by jhawkins002** [comment] 2017-08-04 20:59
@fevangelou Checking in once more. We have a new server deployment in our workflow today, so I wanted to take this opportunity to test Engintron on a completely new environment with next to no competing variables. 

NET::ERR_CERT_AUTHORITY_INVALID errors were encountered upon the AutoSSL certificate installation to the first domain we tested. The Cron did not appear to reliably resolve the issue on it's own. After an hour, we conducted a manual restart of NGINX - which did fix the problem. 

It would definitely appear that something is clearly amiss, unfortunately, that the Cron does not fully address. 

Is there a possibility that PHP-FPM activation may somehow be a related variable? Asking, as I know the addition of that service does add some configuration plumbing to the backend - and all of our domains use it.

**Comment by jhawkins002** [comment] 2017-08-06 22:21
More testing this weekend to report on the fresh server running Engingtron. Again - this is a brand new cPanel server deployed Friday with no other third-party NGINX plugins or other software which interfaces with Apache. 

- Any new domain created never has HTTPS operational in NGINX. The Engintron CRON which runs automatically does not make a difference.  

- We have deployed INCRON scripts which watch the cPanel directories in which SSL certificates are installed and then automatically restart Engintron. Long story short - this works 1 time out of 4. If we change the command to rebuild IP forwarding we get better responses at 2 out of 4 - but it is still not reliable. 

- We are testing a new CRON over the next few days to restart Engintron/Apache every 2 minutes. Between this and the INCRON script we hope to get close to 'on-demand' status for SSL domain availability. 

Something is clearly broken. I think there is a variable we are all missing somewhere. @fevangelou definitely has this working on some hosts, but others such as ours have some type of technology running that seems to interfere with the NGINX restart sequence being of any reliable consequence. I still suspect it may be relevant to the use of PHP-FPM but that is just a hypothesis. 

We, and many other Engintron users, desperately need NGINSX to operate with SSL with more stability than is currently the case. Happy to do whatever we can with the developers to make this a reality.

**Comment by fevangelou** [comment] 2017-08-31 16:43
Engintron operates on dozens of thousands of servers according to my metrics last month I checked. The issue you're dealing with is obviously related to something in your setup. Plus, the code is open to check for bugs. Do you see any?

You mentioned that some 3rd party script called Incron does not work all the time. Why so?

If YOU are the one doing the testing (issuing a cert then check the browser), perhaps you disregard the fact that you could be seeing a cached snapshot of the certificate (self issued or non-existent) in your browser. That's browser behaviour, not Engintron.

**Comment by jhawkins002** [comment] 2017-08-31 17:34
Good points all. If it helps we receive error reports from clients in the field on this issue - in addition to those we report as part of our internal tests. We do try to also verify items we report here among multiple browsers (with flushed caches) and machines first before running the risk of shooting ourselves in the foot by reporting bad data. 

Incron effectively detected the modified certificate folders/locations and ran the Engintron restart but for whatever reason this did not dependably incorporate up newly created certificates. Relying on a time-based Cron has proved reliable.

I do apologize for our continued conversation on an issue that seems to be exotic to only a handful of cases... We have established effective work-arounds that work for us so we will not bother further.

**Comment by barchard** [comment] 2017-08-31 23:11
I don't have any further to add to the issue aside from mentioning that I've seen this issue on my cPanel servers as well. Reloading Engintron/Nginx resolves the issue. The certificate is valid and I only have CSF and the ConfigServer suite of plugins installed. Interesting, it only happened most recently on a user's primary domain but this may be a red herring.

**Comment by brixly** [comment] 2017-11-26 23:04
Resolved in the latest version - update :)

**Closed** 2018-04-04 23:44 UTC
