### ISSUE TITLE
Need to restart nginx/apache everytime ssl certificate changes

### ISSUE THREAD

**Issue by codenamerana** [engintron/engintron#631] opened 2017-08-31 16:31 UTC
Hi,
Very irritating issue i am facing now. Everytime, i update the ssl certificate, it does not show up till i restart nginx/apache in engintron whm interface.

This is very frustrating as i run a hosting company and my clients are always complaining about their new ssl certificates not being updated :(

I need an urgent soluton to this. Rest all is fine till now.

**Comment by jhawkins002** [comment] 2017-08-31 16:41
Same. In our case, we have updated the Engintron cron to run a `/engintron.sh res` command at the top of every hour which seems to resolve the issue. 

It's not on-demand obviously but it's a reasonable enough timeframe for our clients to find acceptable. We initially had this set to run more often, but we had instances where sites were appearing blank or partially-rendered while Apache/NGINX were cycling - so a less frequent restart seemed a reasonable compromise.

**Comment by codenamerana** [comment] 2017-08-31 16:45
Cool. Can you tell me the exact cron so i will add in crontab ?

**Comment by fevangelou** [comment] 2017-08-31 16:53
@codenamerana Verify this https://github.com/engintron/engintron/wiki/SSL-certificate-changes-not-visible-in-Nginx%3F-Here's-a-possible-explanation-&-solution is not the case for you. Read it carefully.

@jhawkins002 That command will simply restart Nginx and Apache. It does not resolve any issues that may stem from browsers caching expired/old/un-issued certificates.

**Comment by codenamerana** [comment] 2017-08-31 16:59
@fevangelou  Hmm, i think i read your solution somewhere many days ago and made sure i saved the crontab file via WHM app only, but it did not work . At first I thought its a weird solution, but well it does not work at all. I tried already :) I will do it again now and let you know.

**Comment by codenamerana** [comment] 2017-08-31 17:35
It failed. I will tell what i did exactly.

Step 1: I went to Engintron interface in WHM and clicked "Update /etc/crontab". It gave a success message.
Step 2: There is a domain which has a self signed certificate auto installed by the system, so when i entered that in browser , it showed insecure .... 
Step 3: I ran "AutoSSL" on that domain and after 10 minutes or so the certificate was issued by Cpanel and i verified from "Manage SSL Hosts" section in WHM.
Step 4: After like 10-15 minutes i refreshed the browser after clearing cache and cookies and typed "https://<domainname>" and got "Your connection is not secure" .... 
Step 5: I restarted nginx/apache and then refreshed the browser and then booom! i can see "Secure Connection" :)

So it is clear that the above solution "Update the crontab file via WHM app" does not work. Please enlighten me what i did wrong or any solution you have as this is very very urgent. If not i will do the cron stuff..

**Comment by georgemoralis** [comment] 2017-09-06 09:31
Same here. Installed a new certificate to review the old one and it wasn't see it

I was forced to create a self-signed one , restart nginx and apache , then install the new one , restart nginx and apache in order to see the new one

Hope it helps others since i spend like 2 hours to figure out this workaround ;)

**Comment by codenamerana** [comment] 2017-09-06 21:27
This is a very serious issue. I am not sure why its still not resolved. Today i did a simple test.

1) I changed ssl cert of a site.
2) I ran this command manually which is run every minute in cron.
/usr/bin/php -c /dev/null /etc/nginx/utilities/https_vhosts.php
3) I got this result.
X-Powered-By: PHP/5.6.31
Content-type: text/html; charset=UTF-8
No changes in Apache's vhosts configuration. HTTPS vhosts for Nginx unchanged.

Hence, the condition if [[ $RUN_CHECK == 1 ]]; is never true so the next statement is never run which is bash /usr/local/src/engintron/engintron.sh purgecache 

@fevangelou can you please look into the issue as urgent as possible ?

Thanks.

**Comment by etechwebcomm** [comment] 2017-09-07 12:22
@codenamerana Thanks for keeping a spotlight on this. I suspect hosts that aren't reporting this problem are either living with the issue assuming it will be patched soon, or they don't have a large  focus on SSL, so they are not as specifically impacted. It happens to be a sticking point for us because we are a university and domain security is a big topic for us. 

Hopefully news on the issue will hit soon. In the meantime, you asked me earlier about the command we used for the hourly restarts. I apologize for getting back to you a bit late, but here is the respective CRON:

`0 * * * * root /engintron.sh res > /dev/null 2>&1`

**Comment by jhawkins002** [comment] 2017-09-07 12:23
@codenamerana Thanks for keeping a spotlight on this. I suspect hosts that aren't reporting this problem are either living with the issue assuming it will be patched soon, or they don't have a large  focus on SSL, so they are not as specifically impacted. It happens to be a sticking point for us because we are a university and domain security is a big topic for us. 

Hopefully news on the issue will hit soon. In the meantime, you asked me earlier about the command we used for the hourly restarts. I apologize for getting back to you a bit late, but here is the respective CRON:

`0 * * * * root /engintron.sh res > /dev/null 2>&1`

**Comment by barchard** [comment] 2017-09-10 14:17
I have this issue as well. 

@jhawkins002 is a complete restart necessary or will a reload work? I find that if I simply reload Nginx the issue goes away. Would a reload be more efficient than a restart?

**Comment by etechwebcomm** [comment] 2017-09-10 20:36
@barchard If I understand you correctly, I think I may have actually used my words badly in my previous note - by restart, I meant restart NGINX/Apache not the entire server.

**Comment by jhawkins002** [comment] 2017-09-10 20:38
Hi @barchard - If I understand you correctly, I think I may have actually used my words badly in my previous note! By restart, I meant restart NGINX/Apache per the "engintron.sh res" command; not rebooting the entire server.

**Comment by barchard** [comment] 2017-09-10 23:46
@jhawkins002 no no, I got that. I wasn't restarting the server :) I was only wondering if reloading Nginx would be *faster* than a full restart. Probably minor and doesn't matter much. As long as the issue is fixed. :) thanks

**Comment by jhawkins002** [comment] 2017-09-11 16:27
@barchard Oh I follow you now! So the "engintron.sh res" command does (I believe) some additional light housekeeping in addition to merely restarting Apache and NGINX - so we did not test just doing a simple, direct NGINX service restart. It's an interesting idea though and we may test it this week. If you happen to do so on your end, please report back your observations!

**Comment by barchard** [comment] 2017-09-11 20:57
@jhawkins002 have you seen #582 and tested [this](https://github.com/engintron/engintron/wiki/Cron-job-to-purge-Nginx-cache-&-temp-files)?

**Comment by jhawkins002** [comment] 2017-09-11 21:32
@barchard Yep! At least for us - purging the cache does not make a reliable difference. We suspect perhaps the problem is not actually with the cache itself, but that NGINX is not always detecting when Apache Virtualhost changes happen for the SSL state of a domain to begin with. The "res" command seems to get the two systems back on the same page.  

There was a working hypothesis in https://github.com/engintron/engintron/issues/582 about the https_vhosts.php script not properly detecting when Virtualhost updates hit but I cannot speak to where that went troubleshooting-wise. 

Side note: we also want as close to on-demand for SSL deployment as we can get, so in our view if we were to constantly dump the cache (say hourly) that somewhat removes a key selling point of having a cache engine to begin with. :)

**Comment by idevwebs** [comment] 2017-09-25 04:26
Has anyone found a WHM SSL hook to attach the restart command to?

**Comment by jhawkins002** [comment] 2017-09-25 16:29
@idevwebs See https://documentation.cpanel.net/display/SDK/Guide+to+Standardized+Hooks+-+Script+Hooks

Unfortunately cPanel has not created dedicated hooks for SSL changes - hence why we, on the user end, and even the Engintron dev had to come up with alternate ways of detecting modifications. You might try adding a -post script for updateuserdomains to see if that gets run whenever certificate changes hit. I do not believe it will, though. :(

**Comment by petarkozic** [comment] 2017-10-09 14:12
Also, I have same problem with SSL.
After SSL installation I must to restart Apache and Nginx.

Can we expect some solution for this in some obviously time ?

P.S. Jun 29th, 2017 - v1.8.4 
Engintron will now flush Nginx's caches and temp files whenever a change is detected in Apache's configuration (and consequently Nginx recreates its vhosts for HTTPS traffic). This resolves issues with newly issued or updated certificates not being reflected in HTTPS traffic served by Nginx.

but this don't work  !

**Comment by jrsarath** [comment] 2017-10-18 21:01
i have this issue too,
Changed SSL won't works without Engintron restart

**Comment by brixly** [comment] 2017-10-18 23:29
This is still an issue for us. Around 40% of our support tickets are required nginx restarts - we are basically running...

https_vhosts.sh 

Running this makes no difference at all. Once this has been ran, we then run the following...

/engintron.sh purgecache

This from what I see restarts nginx rather than reloads and clears the caches down. Isn't this what should happen automatically when a change is detected?

I do feel this one is urgent to get resolved - the Cron isn't the issue here - if the script ran manually doesn't resolve the problem then a further solution is required.

We tell customers that the changes should take around 30 minutes or so, however in most cases customers are waiting 24 hours before contacting us to say they still aren't active - we have been told on a number of occasions this is one of their biggest frustrations with us.

I know we could simply run the purgecache on a scheduled basis through a Cron, but it isn't ideal. I'm not keen on full nginx restarts due to the possibility of nginx syntax errors (normally with SSL certs in configuration). If those errors happen to be there on a restart, then the server is offline.

I get nervous running it manually! 

Please help provide a solution for this

**Comment by jrsarath** [comment] 2017-10-19 11:32
https://github.com/engintron/engintron/issues/662
refer to this issue and lets stay together will find something for sure

**Comment by brixly** [comment] 2017-11-26 23:03
Resolved in the latest version :)

We occasionally (but rarely) get an issue whereby nginx doesn't start back up automatically due to the SSL certificate mismatch in the config files - however, the problem with nginx not restarting was resolved by an update to the latest version

**Comment by lukapaunovic** [comment] 2017-12-09 17:41
Not resolved with latest version 1.8.7

Issue is really annoying :(

**Comment by petarkozic** [comment] 2017-12-09 17:53
Yes, also I have same problem with latest version !

**Comment by brixly** [comment] 2017-12-09 18:03
Are you seeing anything in your /etc/nginx/utilities/https_vhosts.log file? This will let you know if the purgecache is working correctly.

The problem has been resolved for us, however since this has been resolved we are getting a huge number of complaints in regards to 502 errors happening during the purgecache.

**Comment by lukapaunovic** [comment] 2017-12-09 18:08
Purge cache, after it clears cache it restarts nginx and apache and after that SSL is working. 
You can get the same thing by simply doing service nginx restart

What about hooks? Are there any hooks cPanel provided which can help reset nginx after ssl certificate renewal or issuance?

**Comment by brixly** [comment] 2017-12-09 18:48
No there aren't. None that im aware of.

Did you check your logs?

**Comment by nandogameiro** [comment] 2018-01-03 07:18
I have the same issue here, every time that cpanel renews the ssl certs, it's been required to restart nginx to get the new certificate running, otherwise will keep getting the notice certificate expired.

Any solution for that please?

Thanks

**Comment by lukapaunovic** [comment] 2018-01-10 16:22
The only solution that I came up with is this:

`sudo -H -uroot crontab -e`
and then put this in the cron

`0 0 * * * /usr/bin/bash /engintron.sh purgecache`

It will purge cache and restart Nginx once in 24h...

**Comment by brixly** [comment] 2018-01-10 16:30
engintron.sh purgecache should run as part of the https_vhosts.sh called by the cron every minute - as such, it shouldn't be required.

Try this...

grep https_vhosts.sh /var/log/cron to ensure it is running correctly

What I am struggling to understand is, why the purgecache needs to restart nginx at all?

We have replaced our code inside the engintron.sh to use 'nginx reload' instead of 'nginx restart' and have removed the httpd restart entirely.

Since those changes, it has worked perfectly for us.

**Comment by nandogameiro** [comment] 2018-01-11 07:55
`0 0 * * * /usr/bin/bash /engintron.sh purgecache`

The only problem when using this line above on crontab is for me is sometimes nginx won't restart properly, not sure why, even I trying forcing service nginx restart, I think when the nginx is restarted and some websites are being accessed the process stuck and won't stop, for fix it I had to push killall nginx and then the _service nginx restart_ works normally.

Someone knows what we can avoid this issue when using _service nginx restart_ or _/engintron.sh purgecache_?

If I put this on the crontab, I will have to wake up early with my phone ringing with some clients complaining their websites offline =P

See the log below when using _/engintron.sh purgecache_

`httpd restarted successfully.

Restarting Nginx...
Stopping nginx:                                            [FAILED]
Starting nginx: nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:443 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:443 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:443 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:443 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:443 failed (98: Address already in use)
nginx: [emerg] still could not bind()
                                                           [FAILED]
`

**Comment by lukapaunovic** [comment] 2018-01-11 15:42
Uninstall engintron. 
Do

`/scripts/upcp --force`
`/scripts/rebuildhttpdconf`
`service httpd restart`
Then install engintron again.

**Comment by flavioxx** [comment] 2018-01-12 01:25
Has anyone else found a solution to the problem?
The method of uninstalling the engintron and installing again as the @lukapaunovic mentioned above worked?

**Comment by lukapaunovic** [comment] 2018-01-12 03:31
@flavioxx that answer is intended for @nandogameiro 's issue.

My solution for this problem with SSL is to set cron as I mentioned above.
That is a fix for me, at least temporary I do not have to reset nginx manually whenever SSL changes. but still, i do have ssl invalid cert until SSL run.
So I would advise setting the time of the cron AFTER autossl cron runs. so the time without cert is minimal.

**Comment by flavioxx** [comment] 2018-01-12 11:28
@lukapaunovic
For me it did not work put the cron as you mentioned above, I left 1 day and no problem solved. I had to go on engintron in whm and restart nginx + apache so the ssl worked.
remembering that I put my cron to run every 3 hours

**Comment by lukapaunovic** [comment] 2018-01-13 20:10
Well why it wouldn't work? 
This command clears cache + restarts nginx + restarts apache
That's exactly the command I issue when I have that problem.
But I now put it in cron so i do not have to worry about it anymore.

Maybe there's some problem. Change your cron to

`0 0 * * * /usr/bin/bash /engintron.sh purgecache > /tmp/nginx.txt | /usr/bin/mail -E -a /tmp/nginx.txt -s "Nginx Restart" your@gmail.com`

And check the output is it similar as when you run it from termianl.

**Comment by flavioxx** [comment] 2018-01-13 20:42
@lukapaunovic
I saw it in the txt file that is working, I put it every 1 minute to test it.
the strange thing is that I changed the email to my gmail and nothing came, was it to be sent an email to me?

**Comment by lukapaunovic** [comment] 2018-01-13 20:49
It seems in `/engintron.sh` isn't using the full path when calling some commands like `service` or `httpd` that is why your cron failed.

This will work 100%

Run 
`
cd /home && wget https://gist.githubusercontent.com/lukapaunovic/ed8e0175d349dc9762715258be714222/raw/55a5a659841250f7caf56efe2aa31a9d471613e8/cron.sh -O cron.sh && chmod +x ssl-cron.sh`

Now put the cron

`0 * * * * /usr/bin/bash /home/ssl-cron.sh`

This is for every hour. Adjust per your liking.

**Comment by flavioxx** [comment] 2018-01-13 20:55
@lukapaunovic
ready the process and put this other cron ai.
This will solve the problem right now?
Is not it necessary to do anything else?

**Comment by lukapaunovic** [comment] 2018-01-13 20:56
Just run the command, and put the cron it should be fine.
If you ask me I think restarting every 1 hour is too often, I would set it to 12 hours or once in 24h.

**Comment by flavioxx** [comment] 2018-01-13 21:00
in case it is better to put the two crons for 12 hours?
0 * * * * /usr/bin/bash /home/ssl-cron.sh
0 * * * * /usr/bin/bash /engintron.sh purgecache

or just that last one that informed already solves the problem of the engintron?

**Comment by lukapaunovic** [comment] 2018-01-13 21:05
Forget about
`0 * * * * /usr/bin/bash /engintron.sh purgecache`
It won't work, because `service` is not being referenced to by full path and so it doesn't restart nginx.

Leave only 0 0 * * * /usr/bin/bash /home/ssl-cron.sh
Will restart once in 24h.

Also rerun

`wget https://gist.githubusercontent.com/lukapaunovic/ed8e0175d349dc9762715258be714222/raw/0b9a51bbad4e25065cd433d381ed94f8fbbe0232/cron.sh -O /home/ssl-cron.sh && chmod +x /home/ssl-cron.sh`

i remodifyed the file a little.

**Comment by flavioxx** [comment] 2018-01-13 21:15
ready, I just left cron 0 * / 6 * * * / usr / bin / bash /home/ssl-cron.sh
to run from 6 to 6 hours.
and I did what he said
  wget https://gist.githubusercontent.com/lukapaunovic/ed8e0175d349dc9762715258be714222/raw/0b9a51bbad4e25065cd433d381ed94f8fbbe0232/cron.sh -O /home/ssl-cron.sh && chmod + x /home/ssl-cron.sh
Let's see if the problem is solved now. thank you friend

**Comment by lukapaunovic** [comment] 2018-01-13 21:17
Please don't make those spaces, for every six hours it needs to be like this:

`0 */6 * * * /usr/bin/bash /home/ssl-cron.sh`

**Comment by flavioxx** [comment] 2018-01-13 21:22
Thank you, I'm Brazilian and I do not speak English, so I use google translate, it made space when I pasted the translated text here.
thank you friend!

**Comment by flavioxx** [comment] 2018-01-13 21:28
Someone know how to solve the problem of ssl not to install in subdomains cpanel.domain.com
webmail
etc

**Comment by lukapaunovic** [comment] 2018-01-13 21:41
That's probably due AutoSSL unable to verify those domains, or because they miss www alias.

**Comment by flavioxx** [comment] 2018-01-13 21:43
Can you think of a procedure to solve this friend?
Maybe you've thought of something.

**Comment by petarkozic** [comment] 2018-01-14 00:22
AutoSSL don’t cover service cpanel subdomain for any domain as channel,
webmail, etc...


On January 13, 2018 at 10:43:25 PM, flavioxx (notifications@github.com)
wrote:

Can you think of a procedure to solve this friend?
Maybe you've thought of something.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/engintron/engintron/issues/631#issuecomment-357469497>,
or mute the thread

**Comment by flavioxx** [comment] 2018-02-12 20:46
Has the current version released January 19th fixed the problem?
Does anyone know how to tell me?

**Comment by jhawkins002** [comment] 2018-02-12 20:49
@flavioxx It is now working for us!

**Comment by flavioxx** [comment] 2018-02-12 20:54
@jhawkins002
Before I needed to restart nginx, for the certificates to work.
Is it still necessary or is it automatic?
Installing on the server now is everything working correctly or should I do something?

**Comment by jhawkins002** [comment] 2018-02-12 21:02
@flavioxx Certificates now work automatically for us - after the last update. You may have to give it a few seconds, but that is to be expected.

**Comment by flavioxx** [comment] 2018-02-13 13:07
@jhawkins002
I installed Engintron and edited the data.

> #
>  if ($host ~ "fmservidor.com") {
>      set $PROXY_DOMAIN_OR_IP "79.143.187.189";
>  }

I did a test and had to restart nginx for ssl to work.
remembering that I waited 10 hours and today I had to restart for ssl to work in the new domain of a client.
Did I forget some configuration?

**Comment by ayyoobvm** [comment] 2018-03-29 06:29
i have a similar issue everyday Apache goes down at 1 am until manual restart.I am contacted cpanel and many of them are investigated but no one cannot find any resolution.They also scheduled the investigation on at 1 am and filed the problem.But still they cannot find any thing.After reading above commands i adjusted the purge cache cron in to 8 am but still the server down @ 1 am.Sevrer down means apache down.Nginx working so that i got error 502 in clloudflare.I am using engintron dedicated server with php-fpm.Is there any way to fix it?

**Comment by brixly** [comment] 2018-03-29 06:40
Yep, stop AutoSSL and see if it resolves the issue.

**Comment by ayyoobvm** [comment] 2018-03-29 06:45
How to stop auto ssl in cpanel?

**Comment by ayyoobvm** [comment] 2018-03-29 06:49
ok done auto ssl disabled in cpanel.Lets see what will happen today @ 1 am

**Comment by brixly** [comment] 2018-03-29 09:12
Let us know the results :)

The issue I believe I have posted somewhere on here already - AutoSSL doesn't defer the Apache restart, therefore Engintron recognises the change on config and also tries to do the same. It's a loop - although, we are no longer using it because of the issue.

I have made suggestions in the past about the fact nginx restarts instead of reload and the way it issues Apache restarts etc.

Just wasn't quite right somehow but always struggled to get a response from support

**Closed** 2018-04-04 23:44 UTC

**Comment by lukapaunovic** [comment] 2018-04-06 01:31
This is actually still present.
I just witnessed SSL certificate is installed and after 2 hours with the latest version still unsecure.
After nginx reboot, it works.
So this is not fixed.

**Comment by ayyoobvm** [comment] 2018-04-06 11:31
My problem also exist.So i removed engintron.Now bulit in apche only.So there is no problem at midnight.

**Comment by ayyoobvm** [comment] 2018-04-06 11:35
i am contacted cpanel support they figure out the problem




I see the following process just started and Apache went offline:

root      223018  0.0  0.0 108124  1380 ?        SN   01:06   0:00 /bin/bash /etc/nginx/utilities/https_vhosts.sh

It's important to note that cPanel doesn't manage or support Nginx, Engintron, or FleetSSL, so I can't say how these would interact with Apache on a cPanel system.  You may need to do some additional troubleshooting with those scripts as they seem to be the reason that Apache goes offline.
