### ISSUE TITLE
Engintron + Cloudflare High CPU usage

### ISSUE THREAD

**Issue by sioulisn** [engintron/engintron#984] opened 2018-12-28 08:34 UTC
I am using engintron long time without any issues.
Yesterday I added Cloudflare to my server and I set my custom_rules successfully,

What happened is that in the mid of the day with around 50 visitors always at website the CPU reached very high levels (almost all 10 cores at high usage) and the server started to have delays,
I decided to disable the engintron and the server immediately went down to normal CPU usage.

What could possibly happen?

My server:
php7.2 php-fpm fcgi and I use 
Apcu, Redis, OPcache for my cs-cart platform

**Comment by fevangelou** [comment] 2019-01-22 09:20
CloudFlare would certainly not cause issues to Engintron. The problem is somewhere else for sure.

I recommend you use the optimization guides in the Engintron Docs to improve your server's performance.

**Comment by sioulisn** [comment] 2019-01-22 09:35
All this time I have made inspection about the high CPU usage and i found that it is caused from "Passive OS Fingerprinting Daemon". I saw that cPanel fixed an issue they had at apache server causing high CPU by bypassing the checking at ports 80 and 443.

I think that engintron is using 8080 port (?), do you think that this can cause this high CPU issue? When I disable this service "Passive OS Fingerprinting Daemon" then server is going normal.

I am not sever admin expert just trying to find any possible issues that cause that

**Comment by fevangelou** [comment] 2019-01-22 09:37
When Engintron is enabled, it uses ports 80/443 and Apache uses ports 8080/8443. I can't comment on "Passive OS Fingerprinting Daemon" though, you should probably ask cPanel for that.

**Comment by fevangelou** [comment] 2019-03-06 10:31
Closing as resolved.

**Closed by fevangelou** 2019-03-06 10:31 UTC

**Comment by ImLuke954** [comment] 2019-03-08 09:42
I am facing the same issue. When I turn on Cloudflare, it increases CPU usage. With Cloudflare turned off server load reduces drastically for the same amount of traffic.

**Comment by sioulisn** [comment] 2019-03-08 10:12
> I am facing the same issue. When I turn on Cloudflare, it increases CPU usage. With Cloudflare turned off server load reduces drastically for the same amount of traffic.

do you use redis ?

**Comment by fevangelou** [comment] 2019-03-08 12:27
@sioulisn Why would Redis cause issues?

@ImLuke954 There is no reason behind this unless you're using CloudFlare's cPanel plugin or Apache module, in which case a misconfiguration could be causing issues. My guess is that if you use either of these, CloudFlare may be using your server as a distributed cache pool (Railgun). Otherwise, there is practically no reason that switching to CloudFlare would increase your CPU.

**Comment by sioulisn** [comment] 2019-03-08 13:19
@fevangelou at my server I have Cloudflare (with Railgun sometimes or with full cache) + Engintron + Redis + Apcu. Redis RAM is configured well with 3GB.
As I mentioned above I am not expert with servers but I noticed that after my website was getting busy (100 visitors) the CPU was going high for no reason. After I turn off engintron or restart Redis, the  CPU is going to normal level. 
Finally i decided to keep Cloudflare + Engintron + Apcu (with database sessions instead of Redis) along with the great suggestions you have at your docs and everything work super fast and smooth!

Again who read this post, I am not sure if engintron cause this or cloudflare, but 100% the problem is Redis server.

**Comment by fevangelou** [comment] 2019-03-08 13:29
@sioulisn It was clearly Railgun that caused the CPU spikes because it acts as local cache for CloudFlare that does various optimizations to content before sending it over to the CDN. More here: https://www.cloudflare.com/website-optimization/railgun/

As for generic caching on your server, I would recommend Memcached over APCu.

**Comment by sioulisn** [comment] 2019-03-08 13:42
@fevangelou I also have memcached and OPCache!

**Comment by bekgroupservice** [comment] 2019-08-22 17:07
hi mate, 

i have same problem and i think its coming with railgun ! any idea ?

**Comment by sioulisn** [comment] 2019-08-22 19:13
hi m8,
I gave solution to this issue by removing railgun and by using the full page cache in Cloudflare along with engintron (if you have eshop you have to exclude cookies and admin from cloudflare full page cache too).
The ttfb now is 50ms and CPU always at 5% usage.
One more hint if you have much RAM is to use Innodb tables instead of MyISAM. The engintron`s suggested my.cnf works perfect with this configuration.

**Comment by bekgroupservice** [comment] 2019-08-22 21:23
How may i remove Railgun ? All of my sites based on wp and woocommerce and cou usage is 100%

**Comment by bekgroupservice** [comment] 2019-08-22 21:24
Can you share me your my.cnf ?

**Comment by fevangelou** [comment] 2019-08-22 21:36
@bekgroupservice 
```
systemctl stop railgun
systemctl disable railgun
yum remove railgun
```

Look at the Engintron docs for performance suggestions, e.g. https://engintron.com/docs/#/pages/Beyond-Engintron-Optimizing-MySQL

There may also be other components in your server that require optimizing, e.g. Apache, PHP-FPM etc.
