### ISSUE TITLE
Issue with cPanel 68 and installed SSL certificates

### ISSUE THREAD

**Issue by ytlevine** [engintron/engintron#661] opened 2017-10-17 08:16 UTC
My cPanel installations updated themselves to version 68 today.
I'm still running them on EasyApache 3, tried updating to EA4 once, and had trouble, and haven't gotten a chance to go back and try again (and never saw any official recommendations for EA4 here, like the ones that were posted for EA3).

After I restarted the servers, nginx wouldn't start.

The configuration check showed this:
Checking Nginx configuration...
nginx: [emerg] invalid number of arguments in "ssl_certificate_key" directive in /etc/nginx/conf.d/default_https.conf:47
nginx: configuration file /etc/nginx/nginx.conf test failed

After checking the /etc/nginx/conf.d/default_https.conf, the ssl_certificate_key lines were all empty, with just a space afterwards and then a semicolon.

I had been running nginx mainline, and after a bunch of trial and error, the only way to get nginx up by reinstalling nginx stable (I had disabled engintron fully first, though not sure that was necessary).
Even then, the installed ssl certificates weren't being loaded correctly, and I had to switch all my sites on CloudFlare to use the Full SSL setting, instead of using Full (strict), like they had been using.

Any idea what changed in the cPanel 68 update that would break everything?

Thanks a lot!

**Comment by vipxr** [comment] 2017-10-17 08:37
Same here cPanel updated it self to 68 and break everything
all sites goes down until I disabled engintron and they went up
I don't have any Idea about the SSL thing but even websites without SSL went down

**Comment by ytlevine** [comment] 2017-10-17 08:50
Wondering if this might have something to do with a cPanel issue with certificates, which is in turn breaking engintron...

**Comment by vipxr** [comment] 2017-10-17 08:52
I don't think so, another thing I have noticed that the shared IP for the Resellers changed automatically to the server IP

**Comment by rafaelppaulucci** [comment] 2017-10-17 12:09
Same Here!
in /etc/nginx/conf.d/default_https.conf the ssl_certificate_key ; are empty for all users.

How we can solve this? 
regards.

**Comment by bosen** [comment] 2017-10-17 13:51
The problem lies on https_vhosts.php
117&118
`ssl_certificate '.$fullChainCertName.';
ssl_certificate_key '.$vhostCertKeyFile.';`

while cpanel use combined file 
`SSLCertificateFile /var/cpanel/ssl/apache_tls/xx.xx/combined`

And according to 
[http://nginx.org/en/docs/http/configuring_https_servers.html](url)

Can be fixed by 
`ssl_certificate '.$fullChainCertName.';
ssl_certificate_key '.$fullChainCertName.';`

Just need to check the type of the cert that apache using.

Hope this help.

**Comment by rafaelppaulucci** [comment] 2017-10-17 13:55
Worked for me! 👍  Tks @bosen !

**Comment by fevangelou** [comment] 2017-10-17 14:02
@bosen What do you mean when you say "the type of the cert that apache using"? The value `$vhostCertKeyFile` is essentially a concatenated certificate file. Are you referring to a specific SSL certificate provider perhaps?

**Comment by bosen** [comment] 2017-10-17 14:16
@fevangelou hi there, just quick find. 
In 68, (apache 2.4) cpanel use only one file for SSLCertificateFile directive, which is contain key+cert. 
And they not providing SSLCertificateKeyFile directive.

So https_vhosts.php will return blank on providing ssl_certificate_key value.

Above was my quick dirty fix, sorry. 
So i was hoping  https_vhosts.php will have cert type (combined or not) check for generating correct return ssl_certificate_key value.

**Comment by fevangelou** [comment] 2017-10-17 14:20
Can anyone with cPanel v68 email me at _engintron [at] gmail [dot] com_ their vhosts file to have a look at real-world examples of certificate references as constructed by cPanel?

**Comment by bosen** [comment] 2017-10-17 14:23
Here you go @fevangelou 
`  <IfModule ssl_module>`
`    SSLEngine on`
`    SSLCertificateFile /var/cpanel/ssl/apache_tls/xxx.xxx.com/combined`
`    SetEnvIf User-Agent ".*MSIE.*" nokeepalive ssl-unclean-shutdown`
`    <Directory "/var/www/html/cgi-bin">`
`      SSLOptions +StdEnvVars`
`    </Directory>`
`  </IfModule>`

**Comment by fevangelou** [comment] 2017-10-17 14:33
Thanks @bosen (got your email too).

**Comment by fevangelou** [comment] 2017-10-17 15:04
Version 1.8.6 has just been released. Can you please test it out as well?

**Comment by fevangelou** [comment] 2017-10-17 15:09
Changelog here: https://github.com/engintron/engintron/wiki/Changelog#oct-17th-2017---v186

**Comment by ytlevine** [comment] 2017-10-17 15:10
Tried the manual fix earlier, and then tried updating, but still seeing this in the error logs, and sites with full SSL certificates  running through CloudFlare aren't loading;

[error] 7408#7408: *29273 SSL_do_handshake() failed (SSL: error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol) while SSL handshaking to upstream, client: x.x.x.x, server: xxx.com, request: "GET /url/filename HTTP/1.1", upstream: "https://x.x.x.x:8443//url/filename", host: "xxx.com"

Is that a separate issue?

**Comment by bosen** [comment] 2017-10-17 15:25
@ytlevine you need to check nginx configuration from engintron dashboard.

**Comment by ytlevine** [comment] 2017-10-17 15:28
Ran a config check and it comes back fine, found something about setting proxy_ssl_server_name to "on" somewhere for CloudFlare and SNI, not sure why that would change though, and where to put that to try it...

**Comment by bosen** [comment] 2017-10-17 15:40
try curl -v https://x.x.x.x

**Comment by bosen** [comment] 2017-10-17 15:40
@fevangelou thanks for the update, it worked.

**Comment by ytlevine** [comment] 2017-10-17 15:47
Got a SSL error when trying to connect directly to the IP:8443, so there must be a SSL issue further up the line:

* About to connect() to x.x.x.x port 8443 (#0)
*   Trying x.x.x.x... connected
* Connected to  x.x.x.x ( x.x.x.x) port 8443 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* NSS error -12263
* Closing connection #0
* SSL connect error
curl: (35) SSL connect error

**Comment by bosen** [comment] 2017-10-17 15:53
yup its on apache side (since using port 8443), try check if the cert for the domain match with the IP address of the domain.

**Comment by bosen** [comment] 2017-10-17 15:57
im using EA4 :)

**Comment by ytlevine** [comment] 2017-10-17 19:25
In case it helps anyone, opened a ticket with cPanel, they said that the Apache configuration was missing the correct SSLCertificate lines after the update, which seems to be tied to another EA4 issue they're already aware of.

They're still looking at that, but they got it back up and running for now by reverting the httpd.conf file from the rcs file, but it would break again if the configuration is rebuilt, so that still needs to be fixed.

Just figured that might help someone, have to now try that on another server to hopefully fix that as well...

**Comment by ytlevine** [comment] 2017-10-17 20:10
And @fevangelou - just noticing that the CloudFlare list in the default nginx.conf config file is slightly outdated - seems to be a more updated list here: https://support.cloudflare.com/hc/en-us/articles/200170706-How-do-I-restore-original-visitor-IP-with-Nginx-

And had some issues with the originating IPs coming through over the past few months, would switching real_ip_header to CF-Connecting-IP help with that?

Thanks for all your help!

**Comment by virtuali1151** [comment] 2017-10-17 21:00
this is the error I am getting on WHM 68.04, and EA4.

2017/10/16 20:02:01 [emerg] 23611#23611: invalid number of arguments in "ssl_certificate_key" directive in /etc/nginx/conf.d/default_https.conf:47

**Comment by gpant** [comment] 2017-10-19 02:47
Even after the update to 1.8.6 (EA4) I am having the issue of having the wrong path in default_https.conf . 
The script keeps creating each record with:
ssl_certificate /etc/ssl/engintron/....crt; 
and 
ssl_certificate_key /var/cpanel/ssl/installed/keys/{hash_here}.key; 
instead of the correct one
/var/cpanel/ssl/apache_tls/{domain.tld}/combined; 
any ideas?

**Comment by fevangelou** [comment] 2017-10-19 15:55
@gpant This path `/etc/apache2/conf/httpd.conf` is actually the new path used by cPanel but even if you called the old one (inside /usr/...) there was a symlink. I'll update the check to give priority to that path first.

**Comment by fevangelou** [comment] 2017-10-19 16:09
I just pushed a new build. This also increases the check interval from 10 to 15 seconds which should provide some extra time for servers with a large number of domains and whose httpd.conf file takes a little more time to compile than servers with a few dozen domains.

**Comment by fevangelou** [comment] 2017-10-19 16:15
@ytlevine There was only 1 IP change to be exact in the IPv4 pool.

**Comment by ytlevine** [comment] 2017-10-19 16:36
@fevangelou Yeah, but also see that they use real_ip_header CF-Connecting-IP, wondering if that would be better...

**Comment by fevangelou** [comment] 2017-10-19 16:50
That's a less preferred way actually.

**Comment by gpant** [comment] 2017-10-20 08:54
@fevangelou The issue is that in 2 of our servers the symlink was not created by cpanel, its fine of course for most users I guess to use that path.

**Comment by ytlevine** [comment] 2017-10-23 21:16
@fevangelou - thought I responded, whatever works best, had some issues recently with the originating IP not showing up correctly, and had to add code into the wp-config file for a WordPress site, but as long as that's the best option.

And any plans of releasing detailed config recommendations for EA4?
Used your build and recommendations for EA3, and it's been working great, tried upgrading to EA4 and had some issues and ended up rolling back, probably because I didn't have it set up with the best config, would love to see what you recommend...

Thanks for all your awesome work!

**Comment by fevangelou** [comment] 2017-10-26 09:44
@ytlevine It doesn't matter what you have in EA4 for Engintron anymore. And last time I checked, it was impossible to create a "profile" as it was previously possible with EA3.

**Closed by fevangelou** 2017-10-26 09:44 UTC

**Comment by Martin-Blackman** [comment] 2017-11-14 11:26
The issue lies with how Engintron is updating the default_https.conf file.
Each time an SSL is installed or updated, it executes the PHP script to query the Apache configuration and takes parameters from that.

/etc/nginx/utilities/https_vhosts.php

Line 85:

                preg_match("#SSLCertificateKeyFile (.+?)(\n|\r)#s", $vhost, $certkeyfile);

Amend to:
                preg_match("#SSLCertificateFile (.+?)(\n|\r)#s", $vhost, $certkeyfile);

In the original, the "SSLCertificateKeyFile" does not exist in the Apache configuration, as it's using a combined file.

As such, the PHP script output is null for that line.
If we tell it to use the "SSLCertificateFile" it can pull the combined file location and insert that into our default_https.conf.

Fairly simple work-around. :)

**Comment by faca5** [comment] 2017-11-25 13:26
Thank you!

It works.

**Comment by ehcanada** [comment] 2017-12-10 00:23
I already have both codes in our file
                preg_match("#SSLCertificateKeyFile (.+?)(\n|\r)#s", $vhost, $certkeyfile);
                preg_match("#SSLCACertificateFile (.+?)(\n|\r)#s", $vhost, $certcafile);
