### ISSUE TITLE
NETSTAT check for ddos returns 1000 connections from server main IP

### ISSUE THREAD

**Issue by codep0et** [engintron/engintron#721] opened 2018-01-05 17:03 UTC
Hello, I have searched Google and here before posting this.

Running a command like  "netstat -plan|grep :80|awk {'print $5'}|cut -d: -f 1|sort|uniq -c|sort -nk 1"
during a DDoS attack returns a huge amount of connections but coming from my server IP.

Am I doing something wrong to get the connections ? I know Engintron (Nginx) is acting as a proxy, (and I know Engintron is not there to protect me from DDoS :) ), but is there another command I am suppose to be doing ? because obviously it is not normal to have 1000+ connections from the same IP that is my server.

Thanks for the help

**Comment by brixly** [comment] 2018-01-06 01:04
Are your apache logs showing external IP addresses, or your own servers IP address?

It is normal to see more via the internal IP address, but even on larger servers I wouldn't expect it to be that high.

If your apache logs are showing your own servers IP address, then you have an issue with the mod_remoteip

**Comment by iRakic** [comment] 2018-01-07 05:49
It's totally normal to have a lot of connections from your internal/server IP. The Nginx acts as a reverse proxy and it needs to connect to Apache. Basically, if you see a lot of connections from your internal IPs to 8080 and 8443 ports then you don't need to worry.

**Comment by theraw** [comment] 2018-01-07 09:32
@codep0et 
As you're claiming "too much connections" then try `netstat --timers -tn` if you see too much "TIME WAIT"
then use this
`echo 1 > /proc/sys/net/ipv4/tcp_tw_recycle`
What does this do? Just decreases keep alive to `1s` 
Remember that this is just a fast solution as you are searching on google even how to monitor your server on DDoS attack you need someone with knowledge about linux and cpanel to help you.

And please explain well or close this issue because from your explaination this has nothing to do with this repo if you see too much connections from your own server ip, there can be different problems. 
If you again think that this can be caused by engintron then just disable engintron for some moments and see the output of command which you used. And let us know if you was able to see 1000+ connections from different ips and not from your own server ip!
Also keep in mind that `netstat` outputs connections on port :80 directly and has nothing to do with engintron or apache.

**Closed** 2018-04-05 00:25 UTC
