### ISSUE TITLE
[SOLVED] 502 Bad Gateway

### ISSUE THREAD

**Issue by faca5** [engintron/engintron#526] opened 2017-04-16 16:55 UTC
Hello.

We got error:
502 Bad Gateway

Enigtron is behind firewall. (Server ->Firewall -> Internet)

We have solved error with adding port 8080 and 8443 to port forwarding.

[SOLVED]
-----------------------------------------------------------------------------
Instructions:
1. Login in WHM
2. Select Engintron  for cPanel/WHM
3. Select Edit your custom rule
4. Uncomment  set $PROXY_DOMAIN_OR_IP 
5. Add you EXTERNAL IP address  (or INTERNAL IP address if you behind firewall and you like use server only for internal network)

Example:
 set $PROXY_DOMAIN_OR_IP "123.123.123.123"
6. Click to button Update 
7. Click to button Nginx > Restart
8. Visit your site
-----------------------------------------------------------------------------

We found the solution.
WHM > Engintron > Edit your custom rules

We have set "set $PROXY_DOMAIN_OR_IP" and then it starts working without rules on firewall...

Why Enigtron use external IP address and port to works? If should use "localhost" or "127.0.0.1".
How to set Enigtron to use only local traffic to connect to Apache and not external?
How to turn off Google DNS resolver and why is turned on as default?
Why we got error about blind()?
Is there any instructions to optimize settings for high performance?

Log:
2017/04/16 18:46:11 [emerg] 31272#31272: bind() to 0.0.0.0:80 failed (98: Address already in use)
2017/04/16 18:46:11 [emerg] 31272#31272: bind() to 0.0.0.0:443 failed (98: Address already in use)
2017/04/16 18:46:11 [emerg] 31272#31272: bind() to 0.0.0.0:80 failed (98: Address already in use)
2017/04/16 18:46:11 [emerg] 31272#31272: bind() to 0.0.0.0:443 failed (98: Address already in use)
2017/04/16 18:46:11 [emerg] 31272#31272: bind() to 0.0.0.0:80 failed (98: Address already in use)
2017/04/16 18:46:11 [emerg] 31272#31272: bind() to 0.0.0.0:443 failed (98: Address already in use)
2017/04/16 18:46:11 [emerg] 31272#31272: bind() to 0.0.0.0:80 failed (98: Address already in use)
2017/04/16 18:46:11 [emerg] 31272#31272: bind() to 0.0.0.0:443 failed (98: Address already in use)
2017/04/16 18:46:11 [emerg] 31272#31272: bind() to 0.0.0.0:80 failed (98: Address already in use)
2017/04/16 18:46:11 [emerg] 31272#31272: bind() to 0.0.0.0:443 failed (98: Address already in use)
2017/04/16 18:46:11 [emerg] 31272#31272: still could not bind()

2017/04/16 18:46:48 [error] 31332#31332: *1 connect() failed (111: Connection refused) while connecting to upstream, client: INTERNAL IP ADDRESS, server: INTERNAL IP ADDRESS, request: "GET / HTTP/1.1", upstream: "http://EXTERNAL IP ADDRESS:8080/", host: "example.com"

Thank you for this excellent projects!

**Comment by ampedd** [comment] 2017-04-21 23:06
I've been having the exact same problem since I started using engintron.  If somebody comes up for a fix for this so that I dont have our firewalls reflecting the traffic back to our webserver causing unnecessary latency and strain on our firewalls, that would be awesome.

**Comment by faca5** [comment] 2017-04-22 06:16
Hello.

We found the solution.
WHM > Engintron > Edit your custom rules

We have set "set $PROXY_DOMAIN_OR_IP" and then it starts working without rules on firewall...


How we can by-pass Apache and open static files direct with nginx?

**Comment by ampedd** [comment] 2017-04-25 17:48
Hi,

What did you set in the custom rules to make it work properly?  We experimented with this but didn’t have any luck.

Thanks

**Comment by faca5** [comment] 2017-04-25 18:09
Hello.

Internal IP address of server OR external IP of internet.

**Comment by spirogg** [comment] 2017-04-26 02:00
@faca5 https://github.com/engintron/engintron/wiki/Engintron-&-the-%22Custom-Rules%22-file-(for-Nginx)
hope this helps

**Comment by fevangelou** [comment] 2017-04-26 07:41
@faca5 

> How we can by-pass Apache and open static files direct with nginx?
You can't. You'd need to know all site locations and define them in Nginx's configuration. The static cache already does that by saving static files in Nginx's caches for 1 min. You can increase that time in proxy_params_static.

**Comment by djabk** [comment] 2017-05-12 22:46
added but not working 
plz msg  with example

**Comment by faca5** [comment] 2017-05-13 07:08
Hello.

It works!

Instruction in first post.


Yes! We need figure out how to pass "DOCUEMNT_ROOT" to nginx. That can allow us to use "alias" for direct access to the static files.

**Comment by adityakhaire** [comment] 2017-05-13 07:23
details plz

**Comment by faca5** [comment] 2017-05-13 07:27
Did you read first post?

**Comment by fevangelou** [comment] 2017-07-15 18:58
@faca5 If there was a way to do this universally, I would have done it. But it's not possible.

Assuming resolved.

**Closed by fevangelou** 2017-07-15 18:58 UTC

**Comment by galihrezah** [comment] 2018-01-31 22:23
thanks.. fixed now..
use that

**Comment by devteam9200** [comment] 2018-03-07 13:14
Hi All sorry i am new to Github. But we have a WHM server installed with Engintron and Cloud linux. all websites are working fine. Except I am not sure what has happened but now i add new cpanel and that new account will not load any wordpress sites and keep getting 502 Bad gateway error? Can anyone help?

**Comment by Tomicapo** [comment] 2018-10-16 16:12
Hi. I managed to make this work for my main shared IP on an Amazon AWS EC2 instance after hardcoding the main IP like this:
Edit proxy_params_common # LINE 11
from => proxy_pass http://$PROXY_DOMAIN_OR_IP:$PROXY_TO_PORT;
to= > proxy_pass http://[MY SERVER'S PRIVATE IP]:$PROXY_TO_PORT;

The problem is, I have many more IPs for other domains that have dedicated IP. And when I try to browse those domains, I get a "nice" cPanel SORRY! error. If I hardcode that domains IP, it works great, but then I break all the other domains on my main IP.

Any ideas on how to make this dynamic? Or fix it in any way?

**Comment by fevangelou** [comment] 2018-10-16 16:16
Check the "custom rules" file. It's all there.

**Comment by devteam9200** [comment] 2018-12-06 04:12
Hi @denshen a port forward would be dependant on what firewall system you are using. Lets assume you are using csf (as most do as its the best) then what I have added in /etc/csf/csf.allow is the following:

# Engintron Recommended Settings https://engintron.com/docs/#/pages/Restrict-access-to-ports-8080-&-8443-used-by-Apache-only-for-Nginx
tcp|in|d=8080|s=127.0.0.1
tcp|in|d=8080|s=101.0.71.142 
tcp|in|d=8443|s=127.0.0.1
tcp|in|d=8443|s=101.0.71.142

and in /etc/csf/csf.deny the following:

# Engintron Recommended Settings https://engintron.com/docs/#/pages/Restrict-access-to-ports-8080-&-8443-used-by-Apache-only-for-Nginx
tcp|in|d=8080|s=0.0.0.0/0 # do not delete
tcp|in|d=8443|s=0.0.0.0/0 # do not delete

This will allow only Engintron to forward and use the ports 8080 / 8443 to apache 

If you are trying to setup a "Port Forward" this is a slightly different and would depend on the firewall you are using. Example A cisco / fortigate and you want to forward a port to a server then this would need to configure the firewall it self.

I hope this explains?

**Comment by aonbrowser** [comment] 2019-05-22 08:07
Thank you soooo much friend. you save me from a big trouble.

**Comment by u007** [comment] 2020-06-26 15:27
here was my latest update that works:

1. Goto csf firewall, Allow tcp4 OUT port 8080 and 8443 and tcp6 OUT port 8080 and 8443

2. edit csf.allow

```
tcp|in|d=8080|s=127.0.0.1 # The loopback address
tcp|in|d=8080|s=yourpublic_ip # Replace 1.2.3.4 with your server's shared IP - if you have multiple IPs, clone this line and edit the IP
tcp|in|d=8080|s=yourotherpublic_ip
tcp|in|d=8080|s=youripv6ip
tcp|in|d=8443|s=127.0.0.1 # The loopback address
tcp|in|d=8443|s=yourpublic_ip # Replace 1.2.3.4 with your server's shared IP - if you have multiple IPs, clone this line and edit the IP
tcp|in|d=8443|s=yourotherpublic_ip
tcp|in|d=8443|s=youripv6ip
```

3. edit csf.deny

```
# Block all connections to port 8080 except those already allowed in csf.allow
tcp|in|d=8080|s=0.0.0.0/0 # do not delete
# Block all connections to port 8443 except those already allowed in csf.allow
tcp|in|d=8443|s=0.0.0.0/0 # do not delete
```

4. Configure engintron for whm/cpanel
Edit common_http.conf

```
set $PROXY_DOMAIN_OR_IP "yourpublic_ip";
```

**Comment by anoopk350** [comment] 2021-02-25 09:27
> Hello.
> 
> We got error:
> 502 Bad Gateway
> 
> Enigtron is behind firewall. (Server ->Firewall -> Internet)
> 
> We have solved error with adding port 8080 and 8443 to port forwarding.
> 
> ## [SOLVED]
> Instructions:
> 
> 1. Login in WHM
> 2. Select Engintron  for cPanel/WHM
> 3. Select Edit your custom rule
> 4. Uncomment  set $PROXY_DOMAIN_OR_IP
> 5. Add you EXTERNAL IP address  (or INTERNAL IP address if you behind firewall and you like use server only for internal network)
> 
> ## Example:
> set $PROXY_DOMAIN_OR_IP "123.123.123.123"
> 6. Click to button Update
> 7. Click to button Nginx > Restart
> 8. Visit your site
> We found the solution.
> WHM > Engintron > Edit your custom rules
> 
> We have set "set $PROXY_DOMAIN_OR_IP" and then it starts working without rules on firewall...
> 
> Why Enigtron use external IP address and port to works? If should use "localhost" or "127.0.0.1".
> How to set Enigtron to use only local traffic to connect to Apache and not external?
> How to turn off Google DNS resolver and why is turned on as default?
> Why we got error about blind()?
> Is there any instructions to optimize settings for high performance?
> 
> Log:
> 2017/04/16 18:46:11 [emerg] 31272#31272: bind() to 0.0.0.0:80 failed (98: Address already in use)
> 2017/04/16 18:46:11 [emerg] 31272#31272: bind() to 0.0.0.0:443 failed (98: Address already in use)
> 2017/04/16 18:46:11 [emerg] 31272#31272: bind() to 0.0.0.0:80 failed (98: Address already in use)
> 2017/04/16 18:46:11 [emerg] 31272#31272: bind() to 0.0.0.0:443 failed (98: Address already in use)
> 2017/04/16 18:46:11 [emerg] 31272#31272: bind() to 0.0.0.0:80 failed (98: Address already in use)
> 2017/04/16 18:46:11 [emerg] 31272#31272: bind() to 0.0.0.0:443 failed (98: Address already in use)
> 2017/04/16 18:46:11 [emerg] 31272#31272: bind() to 0.0.0.0:80 failed (98: Address already in use)
> 2017/04/16 18:46:11 [emerg] 31272#31272: bind() to 0.0.0.0:443 failed (98: Address already in use)
> 2017/04/16 18:46:11 [emerg] 31272#31272: bind() to 0.0.0.0:80 failed (98: Address already in use)
> 2017/04/16 18:46:11 [emerg] 31272#31272: bind() to 0.0.0.0:443 failed (98: Address already in use)
> 2017/04/16 18:46:11 [emerg] 31272#31272: still could not bind()
> 
> 2017/04/16 18:46:48 [error] 31332#31332: *1 connect() failed (111: Connection refused) while connecting to upstream, client: INTERNAL IP ADDRESS, server: INTERNAL IP ADDRESS, request: "GET / HTTP/1.1", upstream: "http://EXTERNAL IP ADDRESS:8080/", host: "example.com"
> 
> Thank you for this excellent projects!

Its working fine if you have only single shared ip. But its not working if you have any dedicated ipv4 customers/resellers.

**Comment by adrian-alephit** [comment] 2021-03-05 23:11
@anoopk350 
"Its working fine if you have only single shared ip. But its not working if you have any dedicated ipv4 customers/resellers."

I believe your answer may be here: https://github.com/engintron/engintron/issues/75
