### ISSUE TITLE
1.7.3 Mysql restart GUI glitch

### ISSUE THREAD

**Issue by Quazz** [engintron/engintron#322] opened 2016-11-21 11:34 UTC
This only happens when restarting the service through edit my.cnf 

The text of the Mysql service restarting ends up as a sort of overlay on top of everything else, making certain links and actions inaccessible. Refreshing the page obviously resolves this.

**Comment by fevangelou** [comment] 2016-11-21 19:34
If you refer to what shows up AFTER modifying my.cnf, then the bubble should disappear after a couple of seconds. Isn't that the case for you?

**Comment by Quazz** [comment] 2016-11-21 20:58
It disappears, but it bugs out the GUI. I don't have it in front of me right now, but for example, the top Engintron links can no longer be clicked (I'm assuming the "bubble skeleton" remains behind?).

**Comment by fevangelou** [comment] 2016-11-22 14:33
Yeah, it's probably hidden with CSS. I'll add specific dimensions so it doesn't cover the whole page. Thanks for letting me know. Fix should be added in v1.8.0. Closing for now.

**Closed by fevangelou** 2016-11-22 14:33 UTC

**Comment by fevangelou** [comment] 2016-11-22 14:45
Fixed already. If you re-install via Engintron's WHM app you'll see the problem is gone.
