### ISSUE TITLE
Killing Nginx Process Automatically

### ISSUE THREAD

**Issue by rihamd2k** [engintron/engintron#374] opened 2017-01-18 10:33 UTC
Sometimes the Nginx process is getting killed automatically and all websites are going down. When I restart Nginx or do a server reboot website comes back and starts working again. Please investigate this issue. Thanks.

**Comment by jasperthedummy** [comment] 2017-01-20 03:25
@rihamd2k I am experiencing the same issues, but it occurs at random only once every few months.

I am currently investigating if I can use cPanel's `chkservd` daemon to monitor Nginx processes, which I think should be included by default as part of the Engintron installation. `chkservd` is also currently the default way cPanel is monitoring (and killing/restarting) `httpd` and `mysql` processes should they go haywire.

Configuration files for `chkservd` are located in the `/etc/chkserv.d/` folder, organised by the name of the process that is monitored.

Has anyone successfully implemented this and perhaps help shed some light on this?

**Comment by coldplug** [comment] 2017-01-26 00:45
Today failed here also. It would be nice to monitor it with chkserv.d yes. Also simple shell script, either cron based or continously running could check for nginx process and restart daemon if it does not find it.

**Comment by faiznazerali** [comment] 2017-01-26 09:14
I've been getting this issue since I've installed Engintron on my WHM server too. And instead of a server restart, I normally have to just go into the Engitron plugin module, and restart Apache & Nginx - but the issue is, normally it's only when I see a site not responding / down is when I realise that Nginx has failed ... very annoying indeed because the servers' IP are still responsive so no other way to monitor it really .. :(

**Comment by coldplug** [comment] 2017-01-26 09:29
OK... most simple "fix" is this..

#!/bin/bash
# enter endless loop:
while true
do
     if ! pgrep -x "nginx" > /dev/null
     then
         echo `date` "nginx is stopped, restarting..." >> /var/log/nginx_check.log
         service nginx restart
     fi
     sleep 5
done

Put that script into /usr/local/bin/nginx_check.sh
Make it executable:
chmod +x /usr/local/bin/nginx_check.sh

Put it into rc.local for autorun at boot time:
echo "/usr/local/bin/nginx_check.sh &" >> /etc/rc.d/rc.local

Start it manually:
/usr/local/bin/nginx_check.sh &

Or reboot.

Check if /var/log/nginx_check.log exist from time to time to see if there were restarts done by script.

I hope this helps (and that it works, please test) until some come with better solution.

**Comment by faiznazerali** [comment] 2017-01-26 09:35
@coldplug  Thanks for your quick response. I was in the process of creating a script and implementing it via WHM so that chksrvd can be used for monitoring this - http://thecpaneladmin.com/adding-services-to-chksrvd-for-monitoring/

I'll update this ticket once I'm able to complete and run a test on it ...

**Comment by coldplug** [comment] 2017-01-26 09:37
Hi faiznazerali , sure that is better idea to do.

**Comment by faiznazerali** [comment] 2017-01-26 09:58
After some references from here and via the link previously, I've created a monitor via WHM's chksrvd daemon as follows - 

1. Create a script file via ssh in /etc/chkservd.conf/engintron - cmd: "touch /etc/chkservd.com/engintron"
2. Edit the newly created "engintron" file and added the following into it: "service[nginx]=x,x,x,service nginx restart,nginx,root"
3, Edit the file /etc/chkservd.conf - and add the following line to: "engintron:1" - to enable the service file for monitoring
4. Restart the chkservd using the command: "/scripts/restartsrv_chkservd"

Once it's restarted, the service monitoring becomes active and is visible from within WHM » Service Configuration » Service Manager

Hope this helps others .... and I'll keep an eye on this to see if it is as effective (should be).

**Comment by mikeatdesk** [comment] 2017-01-26 11:40
@faiznazerali  Thanks for this. I've added it to my server and hope it'll help auto-restart Engintron the next time it locks up.

**Comment by fevangelou** [comment] 2017-01-26 14:24
Some clarifications... There is already a check for Apache when Engintron is installed. But chkservd pings port 80 for Apache (when Nginx in fact listens to that port - 8080 is for Apache) and if an issue occurs, it restarts Apache.

I'll make sure to address this in v1.8.0 with the Engintron installer creating an "nginx" entry for chkservd.

For those with issues with Nginx getting stuck, I would recommend a "killall nginx" and then "service nginx start" to remove any stuck processes and start Nginx normally.

**Comment by jasperthedummy** [comment] 2017-01-26 14:58
@faiznazerali that's pretty awesome! I'd try that and monitor if it works as expected too.

@fevangelou I realised the port issue too as I was looking through the checks WHM had by default for Apache. Would you recommend changing the port for the daemon to monitor to 8080 for Apache?

**Comment by fevangelou** [comment] 2017-01-26 15:03
@jasperthedummy Correct. Like I said, I'll add this in v1.8.0 of Engintron.

BTW, does anyone (with this issue) have LetsEncrypt with AutoSSL installed & configured?

**Comment by faiznazerali** [comment] 2017-01-26 15:05
@fevangelou yes to both!

**Comment by fevangelou** [comment] 2017-01-26 15:08
I think that is the problem really, not chkservd. There is a cron in cPanel which executes "/usr/local/cpanel/bin/autossl_check --all" periodically. In order for the certificates to work, I think Apache is stopped and a LetsEncrypt process tries to bind to port 80 (to check for available new certificates or renewals), thus causing the issue. I need to investigate further.

**Comment by fevangelou** [comment] 2017-01-26 15:09
Maybe @escherlat (from cPanel) can shed some light on this.

**Comment by escherlat** [comment] 2017-01-26 16:51
autossl_check should not be stopping Apache to attach another process on port 80. Port 80 is checked to verify the domain resolves to the local server but it shouldn't replace what is already bound to port 80 (barring defects and misconfiguration).

I suspect there are still places within cPanel & WHM that the apache_port setting is not properly observed. If anyone encounters such and has steps to reproduce, please don't hesitate to open a bug report with us at https://tickets.cpanel.net

**Comment by rapidcloubr** [comment] 2017-01-27 13:24
@rihamd2k , We're automating the nginx monitoring process, see: https://github.com/engintron/engintron/issues/379

I think it's the same problem we're having.

**Comment by t0mtaylor** [comment] 2017-02-11 12:58
If you follow @faiznazerali steps you can also do a second check for ssl running on port 443:

/etc/chkservd.conf/engintron - cmd: "touch /etc/chkservd.com/engintron-ssl"

`service[nginx]=443,GET / HTTP/1.0,HTTP/1..,service nginx restart,nginx,root`

also dont forget for both files you should create 'echo "+" > /var/run/chkservd/engintron' and 'echo "+" > /var/run/chkservd/engintron-ssl' otherwise it will not appear on the status page!

you should do the same for apache and disable the standard version - you cannot change the port in the existing httpd file, see [https://forums.cpanel.net/threads/chkserv-d-cant-change-default-httpd-port.114701/#post-505781](https://forums.cpanel.net/threads/chkserv-d-cant-change-default-httpd-port.114701/#post-505781)

**Comment by fevangelou** [comment] 2017-02-19 17:15
Nginx will be added to the list of services monitored under cPanel in v1.8.1. Closing for now.

**Closed by fevangelou** 2017-02-19 17:15 UTC
