### ISSUE TITLE
Show compiled and loaded modules

### ISSUE THREAD

**Issue by Nirjonadda** [engintron/engintron#456] opened 2017-03-02 15:13 UTC
Show compiled and loaded modules are showing from Apache section. This 3 setting are not come any output. All are blank, Is this bug or not? 

````
Apache
 Show compiled modules
 Show loaded modules
 Show parsed settings
````
EX: http://image.prntscr.com/image/a29c02a31dc541ad8d8418ca8bbce80e.png

**Comment by fevangelou** [comment] 2017-03-02 16:02
Can you execute e.g. "httpd -t" from the terminal and get any output? What is that output exactly?

**Comment by Nirjonadda** [comment] 2017-03-02 16:10
@fevangelou "httpd -t" output is:

````
[root@na ~]# httpd -t
Syntax OK
[root@na ~]#
````

**Comment by mdvaldosta** [comment] 2017-03-03 01:25
I confirm the same issue, with the same httpd -t output.

**Comment by fevangelou** [comment] 2017-03-03 09:10
Can each one tell me which CentOS version you have and if possible, whether it's 32 or 64 bit architecture?

Simply execute the following command as root user:
```cat /etc/redhat-release && uname -r```

Paste back the output.

**Comment by Nirjonadda** [comment] 2017-03-03 10:09
I am using CentOS 7 64 bit.

**Comment by mdvaldosta** [comment] 2017-03-03 14:34
```
CentOS Linux release 7.3.1611 (Core)
4.9.7-x86_64-linode80
```

**Comment by fevangelou** [comment] 2017-03-03 20:23
I'm afraid I can't reproduce the error on my side. If any of you want me to have a look, you may send root access to engintron at gmail dot com with your GitHub username (so I know who is who). I'll notify you before logging in and I'll certainly won't make any system changes, just run tests.

**Comment by Nirjonadda** [comment] 2017-03-03 20:30
@fevangelou I have send the SSH Access Information. Please let me know that what going on.

**Comment by Nirjonadda** [comment] 2017-03-04 09:36
@fevangelou do you found what is happening? Are you gets my email?

**Comment by Nirjonadda** [comment] 2017-03-04 11:22
@fevangelou Do you still need the SSH Access Information? We need Disable SSH password authentication after your Test.

**Comment by laurfx** [comment] 2017-03-05 01:34
The problem is in the https://github.com/engintron/engintron/blob/master/app/engintron.php on line 177 and so on... , the correct syntax is httpd -t without "service" in front @fevangelou 

@Nirjonadda, edit /usr/local/src/engintron/app/engintron.php with the right syntax and it will work.

**Comment by Nirjonadda** [comment] 2017-03-05 11:20
@laurfx  Still are not working with edit /usr/local/src/engintron/app/engintron.php

````
 case "httpd_status":
        $ret = "<b>Apache Status:</b><br />";
        $ret .= shell_exec("service httpd status");
        break;

    case "httpd_restart":
        $ret = "<b>Restarting Apache...</b><br />";
        $ret .= shell_exec("/scripts/restartsrv_httpd");
        break;

    case "httpd_reload":
        $ret = "<b>Reloading Apache...</b><br />";
        $ret .= shell_exec("service httpd reload");
        $ret .= "Reloading Apache: [  OK  ]";
        break;

    case "httpd_config":
        $ret = "<b>Check configuration for errors...</b><br />";
        $ret .= shell_exec("httpd -t 2>&1");
        break;

    case "httpd_modules_compiled":
        $ret = "<b>Show compiled modules...</b><br />";
        $ret .= shell_exec("httpd -l");
        break;

    case "httpd_modules_loaded":
        $ret = "<b>Show loaded modules...</b><br />";
        $ret .= shell_exec("httpd -M");
        break;

    case "httpd_parsed_settings":
        $ret = "<b>Show parsed settings...</b><br />";
        $ret .= shell_exec("httpd -S");
        break;
````

**Comment by fevangelou** [comment] 2017-03-07 13:15
@Nirjonadda The engintron.php file loaded is in /usr/local/cpanel/whostmgr/docroot/cgi/
@laurfx The syntax is correct as it is. In fact it can work in many ways. Using "service..." allows for the command to work in both initd & systemd systems though (aka CentOS 6 & 7). If it fails for you, please let me know what CentOS version you have.

**Comment by Nirjonadda** [comment] 2017-03-07 16:10
@fevangelou are you doing fix on this issue without manually files edit?

**Comment by laurfx** [comment] 2017-03-09 19:45
@Nirjonadda don't push it, the problem is in your system not Engintron.
@fevangelou Sure, 

`Linux 3.10.0-514.6.1.el7.x86_64 #1 SMP Wed Jan 18 13:06:36 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`
`CentOS Linux release 7.3.1611 (Core) `

Also, when i ran service httpd -t it show me the parameters:
`Usage: httpd {start|stop|restart|condrestart|try-restart|force reload|reload|status|fullstatus|graceful|help|configtest}`

with httpd configtest it's working, maybe it's the httpd version

```
httpd -v
Server version: Apache/2.4.25 (cPanel)
Server built:   Feb 20 2017 23:42:32
```

**Comment by Nirjonadda** [comment] 2017-03-10 05:32
@laurfx Then how to fixing on this issue?

**Comment by laurfx** [comment] 2017-03-10 07:01
You need to run http and see your parameters of your httpd version and
modify the Engintron file.
Or you can make a alias in bash_profile or bashrc

**Comment by fevangelou** [comment] 2017-03-10 14:37
@laurfx I got a KVM based VM running the same CentOS & cPanel releases as you. Here's the output running the exact same commands:

```
$ uname -r && cat /etc/redhat-release && httpd -v && service httpd
3.10.0-514.2.2.el7.x86_64
CentOS Linux release 7.3.1611 (Core) 
Server version: Apache/2.4.25 (Unix)
Server built:   Jan 13 2017 17:32:47
Cpanel::Easy::Apache v3.34.10 rev9999
The service command supports only basic LSB actions (start, stop, restart, try-restart, reload, force-reload, status). For other actions, please try to use systemctl.
```

The kernel is slightly older in my case, but I doubt it would make such a difference.

Go figure...

**Comment by Nirjonadda** [comment] 2017-03-10 17:17
@fevangelou I am using KVM based CentOS 7 & cPanel releases EA4.

````
[root@na ~]# uname -r && cat /etc/redhat-release && httpd -v && service httpd
3.10.0-514.10.2.el7.x86_64
CentOS Linux release 7.3.1611 (Core)
Server version: Apache/2.4.25 (cPanel)
Server built:   Feb 20 2017 23:42:32
The service command supports only basic LSB actions (start, stop, restart, try-restart, reload, force-reload, status). For other actions, please try to use systemctl.
[root@na ~]#

**Comment by laurfx** [comment] 2017-03-15 22:23
I found that a server restart fixes the "issue" perhaps the old binary it gets replaced with the new one after the restart, try to restart the server.

**Comment by fevangelou** [comment] 2017-03-21 05:07
Thanks for the tip @laurfx - did you try @Nirjonadda?

**Comment by Nirjonadda** [comment] 2017-03-21 05:34
@fevangelou What tips you are referring? Doing lots of time server restarts.

**Comment by fevangelou** [comment] 2017-03-21 05:37
I meant, did you try what @laurfx suggested?

I recommend you do a system upgrade from cPanel, then reboot your server.

**Comment by Nirjonadda** [comment] 2017-03-21 17:38
@fevangelou Not work, Only work with this post https://github.com/engintron/engintron/issues/456#issuecomment-284767710

**Comment by fevangelou** [comment] 2017-03-28 12:02
@Nirjonadda OK, one last thing. If you execute "service httpd status" from a terminal, does it output anything?

**Comment by Nirjonadda** [comment] 2017-04-03 21:20
@fevangelou 

````
[root@na /]# service httpd status
Redirecting to /bin/systemctl status  httpd.service
● httpd.service - Apache web server managed by cPanel EasyApache
   Loaded: loaded (/etc/systemd/system/httpd.service; enabled; vendor preset: disabled)
   Active: active (running) since Tue 2017-04-04 03:15:09 +06; 4min 6s ago
  Process: 8560 ExecStart=/usr/local/cpanel/scripts/restartsrv_httpd --no-verbose (code=exited, status=0/SUCCESS)
 Main PID: 8600 (httpd)
   CGroup: /system.slice/httpd.service
           ├─8600 /usr/sbin/httpd -k start
           ├─8601 /usr/local/cpanel/3rdparty/bin/perl /usr/local/cpanel/bin/leechprotect
           ├─8606 /usr/sbin/httpd -k start
           ├─8685 /usr/sbin/httpd -k start
           ├─8726 /usr/sbin/httpd -k start
           ├─8757 /usr/sbin/httpd -k start
           ├─8989 /usr/sbin/httpd -k start
           ├─9107 /usr/sbin/httpd -k start
           ├─9141 /usr/sbin/httpd -k start
           ├─9160 /usr/sbin/httpd -k start
           ├─9209 /usr/sbin/httpd -k start
           ├─9364 /usr/sbin/httpd -k start
           └─9432 /usr/sbin/httpd -k start

Apr 04 03:15:08 na.nirmoladda.com systemd[1]: Starting Apache web server managed by cPanel EasyApache...
Apr 04 03:15:09 na.nirmoladda.com systemd[1]: PID file /run/apache2/httpd.pid not readable (yet?) after start.
Apr 04 03:15:09 na.nirmoladda.com systemd[1]: Started Apache web server managed by cPanel EasyApache.
[root@na /]#
````

**Comment by fevangelou** [comment] 2017-04-12 14:33
I'll add logic to check for the output of these commands in v1.8.4 or v1.9.0.

Closing for now.

**Closed by fevangelou** 2017-04-12 14:33 UTC

**Comment by Nirjonadda** [comment] 2017-04-26 12:08
@fevangelou Do you have plan that when will be happen v1.8.4 or v1.9.0 ?
