### ISSUE TITLE
htaccess optimization cpanel 66.

### ISSUE THREAD

**Issue by zstergios** [engintron/engintron#630] opened 2017-08-30 15:27 UTC
I had issue with htaccess on my cpanel server.
Htaccess are ignored from apache.

I'm posting that issue for everyone that has relegated issue with custom templates that created from nginix.
Also for the developer, may found some good informations.

Reply from cPanel Tech:

> 
> Thank you for your patience as I investigated this issue.
> 
> I found that some custom Apache configuration templates are in use:
> 
> # ls -l /var/cpanel/templates/apache2_4/*.local
> -rw-r--r-- 1 root root 8303 Nov 4 2015 /var/cpanel/templates/apache2_4/ssl_vhost.local
> -rw-r--r-- 1 root root 7441 Nov 4 2015 /var/cpanel/templates/apache2_4/vhost.local
> 
> These custom templates in combination with a new feature that was added in WHM 66 called "htaccess search optimization" resulted in the htaccess files being ignored, because the necessary configuration is missing in the custom configuration:
> 
> https://documentation.cpanel.net/display/66Docs/66+Release+Notes#id-66ReleaseNotes-.htaccesssearchoptimization
> 
> The feature was not immediately enabled after the update to WHM 66. It was enabled after the "Feature Showcase" page was saved on the first login to WHM after the WHM 66 update was completed, where it advertised the feature and asked the administrator if it should be enabled. We have created internal case number CPANEL-15454 regarding this, so that the feature will not be advertised after login to WHM if custom Apache configuration is in use, so that it is less likely that the feature can be enabled in that situation and cause web sites to stop functioning.
> 
> So that web sites would begin working again, I have disabled the new feature by setting WHM >> Home >> Service Configuration >> Apache Configuration >> Global Configuration > Optimize .htaccess (AllowOverride) to 'Search "/" and below (No optimization, Search Full Path)', which gives the previous behavior.
> 
> After you have either removed or updated the custom Apache configuration files that I mentioned above, and then run /scripts/rebuildhttpdconf to update the Apache configuration, it should be safe to change that setting to 'Search "Home Directory" and below (Recommended)', which would provide the new behavior.
> 
> Because the existing custom configuration templates were most likely created as a result of installing the third-party nginx-based accelerator software on this system, it may be necessary to remove the custom template files and then re-install the latest version of the nginx accelerator software so that it will create new custom configuration which is compatible with this new feature.
> 
> Please let me know if you have any questions, if you require any additional assistance, or if you would like for us to close the support request.

**Comment by WebSavvyGuy** [comment] 2017-08-30 17:14
We are getting some issues with our websites also.

Here is CPanels reply:

It looks like this issue may be caused by the following outdated custom Apache templates:

====
[22:19:51 localhost root@8826481 ~]cPs# ls -lahtr /var/cpanel/templates/apache2_4/*.local
-rw-r--r-- 1 root root 7.4K Nov 30  2016 /var/cpanel/templates/apache2_4/vhost.local
-rw-r--r-- 1 root root 8.2K Nov 30  2016 /var/cpanel/templates/apache2_4/ssl_vhost.local
-rw-r----- 1 root root  27K Nov 30  2016 /var/cpanel/templates/apache2_4/ea4_main.local
====

These do not appear to contain the AllowOverride directives from the new 'Optimize .htaccess' feature (and is known to cause 404 errors on subpages if they are not there and the feature is enabled). Would it be OK if we moved these aside, rebuild Apache's configuration, and restart the service? This can also be done by running this command:

# mv -v /var/cpanel/templates/apache2_4/*.local /root/cptechs/; /scripts/rebuildhttpdconf; /scripts/restartsrv_httpd



Hope that helps.   But this new update from WHM is definitely causing issues with Engintron.

**Comment by zstergios** [comment] 2017-08-30 18:25
Yes it causes but not it all servers..until now..

**Comment by fevangelou** [comment] 2017-08-31 15:13
Closing as it's not related to Engintron.

**Closed by fevangelou** 2017-08-31 15:13 UTC

**Comment by zstergios** [comment] 2017-08-31 21:28
@fevangelou Engintron creates custom templates or not?

**Comment by fevangelou** [comment] 2017-09-01 05:28
Can you be more specific please?

On Sep 1, 2017 12:28 AM, "Stergios Zgouletas" <notifications@github.com>
wrote:

@fevangelou <https://github.com/fevangelou> Engintron creates custom
templates or not?

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/engintron/engintron/issues/630#issuecomment-326425479>,
or mute the thread

**Comment by zstergios** [comment] 2017-09-06 11:06
If you run the below command, probably you will see that there are templates that overrides the apache default template. I'm wondering if are created by engitron or by cpanel addon.

ls -lahtr /var/cpanel/templates/apache2_4/*.local

-rw-r--r-- 1 root root 7.4K Nov 30 2016 /var/cpanel/templates/apache2_4/vhost.local
-rw-r--r-- 1 root root 8.2K Nov 30 2016 /var/cpanel/templates/apache2_4/ssl_vhost.local

**Comment by WebSavvyGuy** [comment] 2017-09-07 23:52
Ive been told by a Cpanel tech that "Yes, Engintron affects the Apache configuration templates. "

Take that as you will...just updating this ticket to point that out.
